export type LanguageCode = 'HI' | 'EN' | 'BN' | 'TA' | 'TE' | 'MR' | 'GU' | 'KN' | 'ML' | 'PA' | 'OR' | 'UR';

export interface OnboardingTranslations {
  talkToMe: string;
  talkToMeDesc: string;
  switchToText: string;
  switchToTextDesc: string;
  uploadDocs: string;
  uploadDocsDesc: string;
  listenResponses: string;
  listenResponsesDesc: string;
  skip: string;
  next: string;
  getStarted: string;
  stepOf: string;
}

export interface ConsentTranslations {
  byUsing: string;
  shareLocation: string;
  allowLogging: string;
  helpImprove: string;
  acceptTerms: string;
  agreeToAll: string;
}

export interface LandingTranslations {
  welcome: string;
  tagline: string;
  selectLanguage: string;
  trustedCompanion: string;
  back: string;
  letsChat: string;
  talkToUs: string;
}

export interface AboutTranslations {
  title: string;
  back: string;
  missionTitle: string;
  missionDescription: string;
  createdBy: string;
  creatorDescription: string;
  profile: string;
  feature1Title: string;
  feature1Desc: string;
  feature2Title: string;
  feature2Desc: string;
  feature3Title: string;
  feature3Desc: string;
  footer: string;
}

export interface LanguageConfig {
  code: LanguageCode;
  name: string;
  nativeName: string;
  fontClass: string;
  direction: 'ltr' | 'rtl';
  ttsVoice: string;
  disclaimer: string;
  ui: {
    startConsultation: string;
    tapToSpeak: string;
    listening: string;
    analyzing: string;
    speaking: string;
    uploadDocument: string;
    typeMessage: string;
    send: string;
    emergency: string;
    resources: string;
    info: string;
    admin: string;
    startFresh: string;
    helpline: string;
    attach: string;
    voice: string;
    text: string;
    connected: string;
    offline: string;
    youSaid: string;
    welcomeMessage: string;
    thinking: string;
    processing: string;
    transcribing: string;
    listen: string;
    stop: string;
    references: string;
    newSessionStarted: string;
    newSessionDesc: string;
    onboarding: OnboardingTranslations;
    consent: ConsentTranslations;
    landing: LandingTranslations;
    about: AboutTranslations;
  };
}

export const LANGUAGES: Record<LanguageCode, LanguageConfig> = {
  HI: {
    code: 'HI',
    name: 'Hindi',
    nativeName: 'हिंदी',
    fontClass: 'font-hindi',
    direction: 'ltr',
    ttsVoice: 'hi-IN-Neural2-A',
    disclaimer: 'यह कानूनी सलाह नहीं है। यह केवल सामान्य जानकारी है।',
    ui: {
      startConsultation: 'कानूनी परामर्श शुरू करें',
      tapToSpeak: 'बोलने के लिए टैप करें',
      listening: 'सुन रहा हूँ',
      analyzing: 'विश्लेषण कर रहा हूँ',
      speaking: 'बोल रहा हूँ',
      uploadDocument: 'दस्तावेज़ अपलोड करें',
      typeMessage: 'अपना संदेश लिखें...',
      send: 'भेजें',
      emergency: 'आपातकाल',
      resources: 'संसाधन',
      info: 'जानकारी',
      admin: 'व्यवस्थापक',
      startFresh: 'नया शुरू करें',
      helpline: 'हेल्पलाइन',
      attach: 'संलग्न करें',
      voice: 'आवाज़',
      text: 'टेक्स्ट',
      connected: 'कनेक्टेड',
      offline: 'ऑफ़लाइन',
      youSaid: 'आपने कहा',
      welcomeMessage: 'नमस्ते! मैं न्याय साथी हूँ, आपका कानूनी मित्र। आज आपके मन में क्या है? मैं आपके कानूनी अधिकारों को समझने और किसी भी कानूनी प्रश्न में मार्गदर्शन करने के लिए यहाँ हूँ।',
      thinking: 'सोच रहा हूँ...',
      processing: 'प्रोसेसिंग',
      transcribing: 'लिख रहा हूँ',
      listen: 'सुनें',
      stop: 'रोकें',
      newSessionStarted: 'नया सत्र शुरू हुआ',
      newSessionDesc: 'आपकी बातचीत साफ़ कर दी गई है',
      references: 'संदर्भ',
      onboarding: {
        talkToMe: 'मुझसे बात करो',
        talkToMeDesc: 'बस माइक को टैप करें और अपना सवाल पूछें। एक दोस्त की तरह स्वाभाविक रूप से बोलें!',
        switchToText: 'टेक्स्ट पर स्विच करें',
        switchToTextDesc: 'टाइप करना पसंद है? नीचे की बार में स्विच का उपयोग करके टेक्स्ट मोड पर जाएं।',
        uploadDocs: 'दस्तावेज़ अपलोड करें',
        uploadDocsDesc: 'AI विश्लेषण के लिए कानूनी दस्तावेज़ अपलोड करें। हम PDF, DOCX, XLSX, CSV और छवियों का समर्थन करते हैं।',
        listenResponses: 'जवाब सुनें',
        listenResponsesDesc: 'किसी भी जवाब पर स्पीकर आइकन पर क्लिक करें अपनी भाषा में सुनने के लिए।',
        skip: 'छोड़ें',
        next: 'अगला',
        getStarted: 'शुरू करें',
        stepOf: 'चरण {current} का {total}',
      },
      consent: {
        byUsing: 'न्याय साथी का उपयोग करके, आप सहमत हैं:',
        shareLocation: 'स्थानीय कानूनी सलाह के लिए अपना स्थान साझा करें',
        allowLogging: 'सुरक्षा के लिए गुमनाम कनेक्शन लॉगिंग की अनुमति दें',
        helpImprove: 'सुधार के लिए चैट से सीखने दें (सभी डेटा गुमनाम रहता है)',
        acceptTerms: 'नियम और गोपनीयता नीति स्वीकार करें',
        agreeToAll: 'मैं उपरोक्त सभी से सहमत हूं',
      },
      landing: {
        welcome: 'न्याय साथी में आपका स्वागत है',
        tagline: 'आपकी भाषा में तत्काल कानूनी प्राथमिक चिकित्सा',
        selectLanguage: 'अपनी भाषा चुनें',
        trustedCompanion: 'आपका विश्वसनीय कानूनी प्राथमिक चिकित्सा साथी',
        back: 'वापस',
        letsChat: 'बात करें',
        talkToUs: 'अपने कानूनी प्रश्नों के बारे में हमसे बात करें',
      },
      about: {
        title: 'न्याय साथी के बारे में',
        back: 'वापस',
        missionTitle: 'भारत के लिए कानूनी ज्ञान का लोकतंत्रीकरण',
        missionDescription: 'न्याय साथी सिर्फ एक ऐप नहीं है—यह एक मिशन है। हर भारतीय को उनकी अपनी भाषा में तत्काल, सुलभ और सटीक कानूनी मार्गदर्शन देने के लिए बनाया गया।',
        createdBy: 'वेंकट राम रेड्डी गानुतुला',
        creatorDescription: 'सामाजिक प्रभाव के प्रति जुनूनी, भारत के लिए समाधान बनाने में विश्वास रखते हैं।',
        profile: 'प्रोफ़ाइल',
        feature1Title: 'समावेशी प्रौद्योगिकी',
        feature1Desc: '12+ भारतीय भाषाओं के समर्थन से भाषा बाधाओं को तोड़ना, हर नागरिक को कानूनी जानकारी सुलभ बनाना।',
        feature2Title: 'सशक्तिकरण',
        feature2Desc: 'जटिल कानूनी शब्दावली को सरल, कार्रवाई योग्य सलाह में बदलना जो कोई भी समझ सके।',
        feature3Title: 'सहानुभूति से सेवा',
        feature3Desc: 'एक AI साथी जो पहले सुनता है, आपकी स्थिति समझता है, और देखभाल के साथ मार्गदर्शन प्रदान करता है।',
        footer: 'वेंकट राम रेड्डी गानुतुला द्वारा भारत के लिए ❤️ से निर्मित',
      },
    },
  },
  EN: {
    code: 'EN',
    name: 'English',
    nativeName: 'English',
    fontClass: 'font-sans',
    direction: 'ltr',
    ttsVoice: 'en-IN-Neural2-A',
    disclaimer: 'This is NOT legal advice. General information only.',
    ui: {
      startConsultation: 'Start Legal Consultation',
      tapToSpeak: 'Tap to speak',
      listening: 'Listening',
      analyzing: 'Analyzing',
      speaking: 'Speaking',
      uploadDocument: 'Upload Document',
      typeMessage: 'Type your message...',
      send: 'Send',
      emergency: 'Emergency',
      resources: 'Resources',
      info: 'Info',
      admin: 'Admin',
      startFresh: 'Start Fresh',
      helpline: 'Helpline',
      attach: 'Attach',
      voice: 'Voice',
      text: 'Text',
      connected: 'Connected',
      offline: 'Offline',
      youSaid: 'YOU SAID',
      welcomeMessage: "Hey there! I'm Nyay Saathi, your legal buddy. What's on your mind today? I'm here to help you understand your legal rights and guide you through any legal questions you might have.",
      thinking: 'Thinking...',
      processing: 'Processing',
      transcribing: 'Transcribing',
      listen: 'Listen',
      stop: 'Stop',
      references: 'References',
      newSessionStarted: 'New session started',
      newSessionDesc: 'Your conversation has been cleared',
      onboarding: {
        talkToMe: 'Talk to Me',
        talkToMeDesc: 'Just tap the mic and ask your question. Speak naturally like you would to a friend!',
        switchToText: 'Switch to Text',
        switchToTextDesc: 'Prefer typing? Toggle to text mode using the switch in the bottom bar.',
        uploadDocs: 'Upload Documents',
        uploadDocsDesc: 'Upload legal documents for AI analysis. We support PDF, DOCX, XLSX, CSV, and images.',
        listenResponses: 'Listen to Responses',
        listenResponsesDesc: 'Click the speaker icon on any response to hear it in your language.',
        skip: 'Skip',
        next: 'Next',
        getStarted: 'Get Started',
        stepOf: 'Step {current} of {total}',
      },
      consent: {
        byUsing: 'By using Nyay Saathi, you agree to:',
        shareLocation: 'Share your location for relevant local legal advice',
        allowLogging: 'Allow anonymous connection logging for security',
        helpImprove: 'Let us learn from chats to improve (all data stays anonymous)',
        acceptTerms: 'Accept the Terms and Privacy Policy',
        agreeToAll: 'I agree to all of the above',
      },
      landing: {
        welcome: 'Welcome to Nyay Saathi',
        tagline: 'Instant legal first-aid in your language',
        selectLanguage: 'Select your language',
        trustedCompanion: 'Your trusted legal first-aid companion',
        back: 'Back',
        letsChat: "Let's Chat",
        talkToUs: 'Talk to us about your legal questions',
      },
      about: {
        title: 'About Nyay Saathi',
        back: 'Back',
        missionTitle: 'Democratizing Legal Knowledge for Bharat',
        missionDescription: "Nyay Saathi is more than just an app—it's a mission. Built to give every Indian instant, accessible, and accurate legal guidance in their own language.",
        createdBy: 'Venkat Ram Reddy Ganuthula',
        creatorDescription: 'Passionate about social impact, believes in building Solutions for Bharat.',
        profile: 'Profile',
        feature1Title: 'Inclusive Technology',
        feature1Desc: 'Breaking language barriers with support for 12+ Indian languages, making legal information accessible to every citizen.',
        feature2Title: 'Empowerment',
        feature2Desc: 'Turning confusing legal jargon into simple, actionable advice that anyone can understand.',
        feature3Title: 'Served with Empathy',
        feature3Desc: 'An AI companion that listens first, understands your situation, and provides guidance with care.',
        footer: 'Built with ❤️ for Bharat by Venkat Ram Reddy Ganuthula',
      },
    },
  },
  BN: {
    code: 'BN',
    name: 'Bengali',
    nativeName: 'বাংলা',
    fontClass: 'font-bengali',
    direction: 'ltr',
    ttsVoice: 'bn-IN-Wavenet-A',
    disclaimer: 'এটি আইনি পরামর্শ নয়। শুধুমাত্র সাধারণ তথ্য।',
    ui: {
      startConsultation: 'আইনি পরামর্শ শুরু করুন',
      tapToSpeak: 'কথা বলতে ট্যাপ করুন',
      listening: 'শুনছি',
      analyzing: 'বিশ্লেষণ করছি',
      speaking: 'বলছি',
      uploadDocument: 'নথি আপলোড করুন',
      typeMessage: 'আপনার বার্তা লিখুন...',
      send: 'পাঠান',
      emergency: 'জরুরি',
      resources: 'সম্পদ',
      info: 'তথ্য',
      admin: 'অ্যাডমিন',
      startFresh: 'নতুন শুরু',
      helpline: 'হেল্পলাইন',
      attach: 'সংযুক্ত করুন',
      voice: 'ভয়েস',
      text: 'টেক্সট',
      connected: 'সংযুক্ত',
      offline: 'অফলাইন',
      youSaid: 'আপনি বলেছেন',
      welcomeMessage: 'হ্যালো! আমি ন্যায় সাথী, আপনার আইনি বন্ধু। আজ আপনার মনে কী আছে? আমি আপনার আইনি অধিকার বুঝতে এবং আপনার আইনি প্রশ্নে সাহায্য করতে এখানে আছি।',
      thinking: 'ভাবছি...',
      processing: 'প্রক্রিয়াকরণ',
      transcribing: 'লিখছি',
      listen: 'শুনুন',
      stop: 'বন্ধ করুন',
      references: 'তথ্যসূত্র',
      newSessionStarted: 'নতুন সেশন শুরু হয়েছে',
      newSessionDesc: 'আপনার কথোপকথন মুছে ফেলা হয়েছে',
      onboarding: {
        talkToMe: 'আমার সাথে কথা বলুন',
        talkToMeDesc: 'শুধু মাইক ট্যাপ করুন এবং আপনার প্রশ্ন জিজ্ঞাসা করুন। বন্ধুর মতো স্বাভাবিকভাবে কথা বলুন!',
        switchToText: 'টেক্সটে স্যুইচ করুন',
        switchToTextDesc: 'টাইপ করতে পছন্দ করেন? নিচের বারে সুইচ ব্যবহার করে টেক্সট মোডে যান।',
        uploadDocs: 'নথি আপলোড করুন',
        uploadDocsDesc: 'AI বিশ্লেষণের জন্য আইনি নথি আপলোড করুন। আমরা PDF, DOCX, XLSX, CSV এবং ছবি সমর্থন করি।',
        listenResponses: 'উত্তর শুনুন',
        listenResponsesDesc: 'আপনার ভাষায় শুনতে যেকোনো উত্তরে স্পিকার আইকনে ক্লিক করুন।',
        skip: 'এড়িয়ে যান',
        next: 'পরবর্তী',
        getStarted: 'শুরু করুন',
        stepOf: 'ধাপ {current} এর {total}',
      },
      consent: {
        byUsing: 'ন্যায় সাথী ব্যবহার করে, আপনি সম্মত হচ্ছেন:',
        shareLocation: 'প্রাসঙ্গিক স্থানীয় আইনি পরামর্শের জন্য আপনার অবস্থান শেয়ার করুন',
        allowLogging: 'নিরাপত্তার জন্য বেনামী সংযোগ লগিং এর অনুমতি দিন',
        helpImprove: 'উন্নতির জন্য চ্যাট থেকে শিখতে দিন (সমস্ত ডেটা বেনামী থাকে)',
        acceptTerms: 'শর্তাবলী এবং গোপনীয়তা নীতি স্বীকার করুন',
        agreeToAll: 'আমি উপরের সবকিছুতে সম্মত',
      },
      landing: {
        welcome: 'ন্যায় সাথীতে স্বাগতম',
        tagline: 'আপনার ভাষায় তাৎক্ষণিক আইনি প্রাথমিক চিকিৎসা',
        selectLanguage: 'আপনার ভাষা নির্বাচন করুন',
        trustedCompanion: 'আপনার বিশ্বস্ত আইনি প্রাথমিক চিকিৎসা সঙ্গী',
        back: 'পিছনে',
        letsChat: 'চ্যাট করুন',
        talkToUs: 'আপনার আইনি প্রশ্ন সম্পর্কে আমাদের সাথে কথা বলুন',
      },
      about: {
        title: 'ন্যায় সাথী সম্পর্কে',
        back: 'পিছনে',
        missionTitle: 'ভারতের জন্য আইনি জ্ঞানের গণতন্ত্রীকরণ',
        missionDescription: 'ন্যায় সাথী শুধু একটি অ্যাপ নয়—এটি একটি মিশন। প্রতিটি ভারতীয়কে তাদের নিজের ভাষায় তাৎক্ষণিক, সুলভ এবং সঠিক আইনি নির্দেশনা দিতে তৈরি।',
        createdBy: 'ভেঙ্কট রাম রেড্ডি গানুতুলা',
        creatorDescription: 'সামাজিক প্রভাবের প্রতি আগ্রহী, ভারতের জন্য সমাধান তৈরিতে বিশ্বাসী।',
        profile: 'প্রোফাইল',
        feature1Title: 'অন্তর্ভুক্তিমূলক প্রযুক্তি',
        feature1Desc: '১২+ ভারতীয় ভাষার সমর্থনে ভাষার বাধা ভেঙে, প্রতিটি নাগরিকের কাছে আইনি তথ্য সুলভ করা।',
        feature2Title: 'ক্ষমতায়ন',
        feature2Desc: 'জটিল আইনি শব্দকে সহজ, কার্যকর পরামর্শে রূপান্তরিত করা যা যে কেউ বুঝতে পারে।',
        feature3Title: 'সহানুভূতির সাথে সেবা',
        feature3Desc: 'একটি AI সঙ্গী যে প্রথমে শোনে, আপনার পরিস্থিতি বোঝে এবং যত্ন সহকারে নির্দেশনা দেয়।',
        footer: 'ভেঙ্কট রাম রেড্ডি গানুতুলা দ্বারা ভারতের জন্য ❤️ দিয়ে তৈরি',
      },
    },
  },
  TA: {
    code: 'TA',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    fontClass: 'font-tamil',
    direction: 'ltr',
    ttsVoice: 'ta-IN-Wavenet-A',
    disclaimer: 'இது சட்ட ஆலோசனை அல்ல। பொது தகவல் மட்டுமே।',
    ui: {
      startConsultation: 'சட்ட ஆலோசனை தொடங்கு',
      tapToSpeak: 'பேச தட்டவும்',
      listening: 'கேட்கிறேன்',
      analyzing: 'பகுப்பாய்வு செய்கிறேன்',
      speaking: 'பேசுகிறேன்',
      uploadDocument: 'ஆவணத்தை பதிவேற்றவும்',
      typeMessage: 'உங்கள் செய்தியை எழுதுங்கள்...',
      send: 'அனுப்பு',
      emergency: 'அவசரம்',
      resources: 'வளங்கள்',
      info: 'தகவல்',
      admin: 'நிர்வாகி',
      startFresh: 'புதிதாக தொடங்கு',
      helpline: 'உதவி எண்',
      attach: 'இணைக்கவும்',
      voice: 'குரல்',
      text: 'உரை',
      connected: 'இணைக்கப்பட்டது',
      offline: 'ஆஃப்லைன்',
      youSaid: 'நீங்கள் சொன்னது',
      welcomeMessage: 'வணக்கம்! நான் நியாய சாதி, உங்கள் சட்ட நண்பன். இன்று உங்கள் மனதில் என்ன இருக்கிறது? உங்கள் சட்ட உரிமைகளை புரிந்துகொள்ள உதவ நான் இங்கே இருக்கிறேன்.',
      thinking: 'யோசிக்கிறேன்...',
      processing: 'செயலாக்கம்',
      transcribing: 'எழுதுகிறேன்',
      listen: 'கேளுங்கள்',
      stop: 'நிறுத்து',
      references: 'குறிப்புகள்',
      newSessionStarted: 'புதிய அமர்வு தொடங்கியது',
      newSessionDesc: 'உங்கள் உரையாடல் அழிக்கப்பட்டது',
      onboarding: {
        talkToMe: 'என்னிடம் பேசுங்கள்',
        talkToMeDesc: 'மைக்கை தட்டி உங்கள் கேள்வியை கேளுங்கள். நண்பரிடம் பேசுவது போல் இயல்பாக பேசுங்கள்!',
        switchToText: 'உரைக்கு மாறவும்',
        switchToTextDesc: 'டைப் செய்ய விரும்புகிறீர்களா? கீழே உள்ள பட்டியில் சுவிட்சைப் பயன்படுத்தி உரை பயன்முறைக்கு மாறவும்.',
        uploadDocs: 'ஆவணங்களை பதிவேற்றவும்',
        uploadDocsDesc: 'AI பகுப்பாய்வுக்கு சட்ட ஆவணங்களை பதிவேற்றவும். PDF, DOCX, XLSX, CSV மற்றும் படங்களை ஆதரிக்கிறோம்.',
        listenResponses: 'பதில்களை கேளுங்கள்',
        listenResponsesDesc: 'உங்கள் மொழியில் கேட்க எந்த பதிலிலும் ஸ்பீக்கர் ஐகானை கிளிக் செய்யவும்.',
        skip: 'தவிர்',
        next: 'அடுத்து',
        getStarted: 'தொடங்கு',
        stepOf: 'படி {current} இல் {total}',
      },
      consent: {
        byUsing: 'நியாய சாதி பயன்படுத்துவதன் மூலம், நீங்கள் ஒப்புக்கொள்கிறீர்கள்:',
        shareLocation: 'தொடர்புடைய உள்ளூர் சட்ட ஆலோசனைக்கு உங்கள் இருப்பிடத்தைப் பகிரவும்',
        allowLogging: 'பாதுகாப்பிற்கான அநாமதேய இணைப்பு பதிவை அனுமதிக்கவும்',
        helpImprove: 'மேம்படுத்த அரட்டைகளிலிருந்து கற்றுக்கொள்ள அனுமதிக்கவும் (எல்லா தரவும் அநாமதேயமாக இருக்கும்)',
        acceptTerms: 'விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கவும்',
        agreeToAll: 'மேலே உள்ள அனைத்திற்கும் ஒப்புக்கொள்கிறேன்',
      },
      landing: {
        welcome: 'நியாய சாதிக்கு வரவேற்கிறோம்',
        tagline: 'உங்கள் மொழியில் உடனடி சட்ட முதலுதவி',
        selectLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுங்கள்',
        trustedCompanion: 'உங்கள் நம்பகமான சட்ட முதலுதவி தோழன்',
        back: 'பின்னால்',
        letsChat: 'பேசலாம்',
        talkToUs: 'உங்கள் சட்ட கேள்விகள் பற்றி எங்களிடம் பேசுங்கள்',
      },
      about: {
        title: 'நியாய சாதி பற்றி',
        back: 'பின்னால்',
        missionTitle: 'பாரதத்திற்கான சட்ட அறிவின் ஜனநாயகமயமாக்கல்',
        missionDescription: 'நியாய சாதி வெறும் ஆப் அல்ல—இது ஒரு இயக்கம். ஒவ்வொரு இந்தியருக்கும் அவரவர் மொழியில் உடனடி, எளிமையான, துல்லியமான சட்ட வழிகாட்டுதலை வழங்க உருவாக்கப்பட்டது.',
        createdBy: 'வெங்கட் ராம் ரெட்டி கனுதுலா',
        creatorDescription: 'சமூக தாக்கத்தில் ஆர்வமுள்ள, பாரதத்திற்கான தீர்வுகளை உருவாக்குவதில் நம்பிக்கை கொண்டவர்.',
        profile: 'சுயவிவரம்',
        feature1Title: 'உள்ளடக்கிய தொழில்நுட்பம்',
        feature1Desc: '12+ இந்திய மொழிகளின் ஆதரவுடன் மொழி தடைகளை உடைத்து, ஒவ்வொரு குடிமகனுக்கும் சட்ட தகவல்களை அணுகக்கூடியதாக்குகிறது.',
        feature2Title: 'அதிகாரமளித்தல்',
        feature2Desc: 'குழப்பமான சட்ட சொற்களை யாரும் புரிந்துகொள்ளக்கூடிய எளிய, செயல்படுத்தக்கூடிய ஆலோசனையாக மாற்றுகிறது.',
        feature3Title: 'அனுதாபத்துடன் சேவை',
        feature3Desc: 'முதலில் கேட்கும், உங்கள் நிலையைப் புரிந்துகொள்ளும், அக்கறையுடன் வழிகாட்டும் AI தோழன்.',
        footer: 'வெங்கட் ராம் ரெட்டி கனுதுலா ❤️ உடன் பாரதத்திற்காக உருவாக்கியது',
      },
    },
  },
  TE: {
    code: 'TE',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    fontClass: 'font-telugu',
    direction: 'ltr',
    ttsVoice: 'te-IN-Standard-A',
    disclaimer: 'ఇది చట్టపరమైన సలహా కాదు. సాధారణ సమాచారం మాత్రమే.',
    ui: {
      startConsultation: 'చట్టపరమైన సలహా ప్రారంభించండి',
      tapToSpeak: 'మాట్లాడటానికి నొక్కండి',
      listening: 'వింటున్నాను',
      analyzing: 'విశ్లేషిస్తున్నాను',
      speaking: 'మాట్లాడుతున్నాను',
      uploadDocument: 'పత్రం అప్‌లోడ్ చేయండి',
      typeMessage: 'మీ సందేశం టైప్ చేయండి...',
      send: 'పంపండి',
      emergency: 'అత్యవసర',
      resources: 'వనరులు',
      info: 'సమాచారం',
      admin: 'నిర్వాహకుడు',
      startFresh: 'కొత్తగా ప్రారంభించు',
      helpline: 'హెల్ప్‌లైన్',
      attach: 'జోడించు',
      voice: 'వాయిస్',
      text: 'టెక్స్ట్',
      connected: 'కనెక్ట్ అయింది',
      offline: 'ఆఫ్‌లైన్',
      youSaid: 'మీరు చెప్పారు',
      welcomeMessage: 'హలో! నేను న్యాయ సాథి, మీ చట్టపరమైన మిత్రుడు. ఈరోజు మీ మనసులో ఏముంది? మీ చట్టపరమైన హక్కులను అర్థం చేసుకోవడంలో సహాయం చేయడానికి నేను ఇక్కడ ఉన్నాను.',
      thinking: 'ఆలోచిస్తున్నాను...',
      processing: 'ప్రాసెసింగ్',
      transcribing: 'రాస్తున్నాను',
      listen: 'వినండి',
      stop: 'ఆపు',
      references: 'సూచనలు',
      newSessionStarted: 'కొత్త సెషన్ ప్రారంభమైంది',
      newSessionDesc: 'మీ సంభాషణ తొలగించబడింది',
      onboarding: {
        talkToMe: 'నాతో మాట్లాడండి',
        talkToMeDesc: 'మైక్ ను ట్యాప్ చేసి మీ ప్రశ్న అడగండి. స్నేహితుడితో మాట్లాడినట్లు సహజంగా మాట్లాడండి!',
        switchToText: 'టెక్స్ట్ కు మారండి',
        switchToTextDesc: 'టైప్ చేయడం ఇష్టపడతారా? దిగువ బార్‌లో స్విచ్ ఉపయోగించి టెక్స్ట్ మోడ్‌కు మారండి.',
        uploadDocs: 'డాక్యుమెంట్లు అప్‌లోడ్ చేయండి',
        uploadDocsDesc: 'AI విశ్లేషణ కోసం చట్టపరమైన డాక్యుమెంట్లను అప్‌లోడ్ చేయండి. మేము PDF, DOCX, XLSX, CSV మరియు చిత్రాలకు మద్దతు ఇస్తాము.',
        listenResponses: 'స్పందనలు వినండి',
        listenResponsesDesc: 'మీ భాషలో వినడానికి ఏదైనా స్పందనపై స్పీకర్ ఐకాన్ క్లిక్ చేయండి.',
        skip: 'దాటవేయి',
        next: 'తదుపరి',
        getStarted: 'ప్రారంభించండి',
        stepOf: 'దశ {current} లో {total}',
      },
      consent: {
        byUsing: 'న్యాయ సాథి ఉపయోగించడం ద్వారా, మీరు అంగీకరిస్తున్నారు:',
        shareLocation: 'సంబంధిత స్థానిక చట్ట సలహా కోసం మీ స్థానాన్ని షేర్ చేయండి',
        allowLogging: 'భద్రత కోసం అనామక కనెక్షన్ లాగింగ్‌ను అనుమతించండి',
        helpImprove: 'మెరుగుపరచడానికి చాట్‌ల నుండి నేర్చుకోనివ్వండి (అన్ని డేటా అనామకంగా ఉంటుంది)',
        acceptTerms: 'నిబంధనలు మరియు గోప్యతా విధానాన్ని అంగీకరించండి',
        agreeToAll: 'పైన ఉన్న అన్నింటికీ అంగీకరిస్తున్నాను',
      },
      landing: {
        welcome: 'న్యాయ సాథికి స్వాగతం',
        tagline: 'మీ భాషలో తక్షణ చట్ట ప్రథమ చికిత్స',
        selectLanguage: 'మీ భాషను ఎంచుకోండి',
        trustedCompanion: 'మీ నమ్మకమైన చట్ట ప్రథమ చికిత్స సహచరుడు',
        back: 'వెనుకకు',
        letsChat: 'మాట్లాడదాం',
        talkToUs: 'మీ చట్ట ప్రశ్నల గురించి మాతో మాట్లాడండి',
      },
      about: {
        title: 'న్యాయ సాథి గురించి',
        back: 'వెనుకకు',
        missionTitle: 'భారత్ కోసం చట్ట జ్ఞానాన్ని ప్రజాస్వామ్యం చేయడం',
        missionDescription: 'న్యాయ సాథి కేవలం యాప్ కాదు—ఇది ఒక మిషన్. ప్రతి భారతీయుడికి వారి స్వంత భాషలో తక్షణ, అందుబాటులో ఉన్న, ఖచ్చితమైన చట్ట మార్గదర్శకత్వం అందించడానికి నిర్మించబడింది.',
        createdBy: 'వెంకట్ రామ్ రెడ్డి గానుతుల',
        creatorDescription: 'సామాజిక ప్రభావంపై ఆసక్తిగలవారు, భారత్ కోసం పరిష్కారాలను నిర్మించడంలో నమ్మకం.',
        profile: 'ప్రొఫైల్',
        feature1Title: 'సమగ్ర సాంకేతికత',
        feature1Desc: '12+ భారతీయ భాషల మద్దతుతో భాషా అడ్డంకులను తొలగించి, ప్రతి పౌరుడికి చట్ట సమాచారాన్ని అందుబాటులో ఉంచడం.',
        feature2Title: 'సాధికారత',
        feature2Desc: 'గందరగోళ చట్ట పదజాలాన్ని ఎవరైనా అర్థం చేసుకోగల సరళమైన, చర్య తీసుకోగల సలహాగా మార్చడం.',
        feature3Title: 'సానుభూతితో సేవ',
        feature3Desc: 'మొదట వినే, మీ పరిస్థితిని అర్థం చేసుకునే, శ్రద్ధతో మార్గదర్శకత్వం అందించే AI సహచరుడు.',
        footer: 'వెంకట్ రామ్ రెడ్డి గానుతుల ❤️ తో భారత్ కోసం నిర్మించబడింది',
      },
    },
  },
  MR: {
    code: 'MR',
    name: 'Marathi',
    nativeName: 'मराठी',
    fontClass: 'font-hindi',
    direction: 'ltr',
    ttsVoice: 'mr-IN-Wavenet-A',
    disclaimer: 'हा कायदेशीर सल्ला नाही. केवळ सामान्य माहिती.',
    ui: {
      startConsultation: 'कायदेशीर सल्ला सुरू करा',
      tapToSpeak: 'बोलण्यासाठी टॅप करा',
      listening: 'ऐकत आहे',
      analyzing: 'विश्लेषण करत आहे',
      speaking: 'बोलत आहे',
      uploadDocument: 'दस्तऐवज अपलोड करा',
      typeMessage: 'तुमचा संदेश टाइप करा...',
      send: 'पाठवा',
      emergency: 'आणीबाणी',
      resources: 'संसाधने',
      info: 'माहिती',
      admin: 'प्रशासक',
      startFresh: 'नव्याने सुरू करा',
      helpline: 'हेल्पलाइन',
      attach: 'जोडा',
      voice: 'आवाज',
      text: 'मजकूर',
      connected: 'कनेक्ट',
      offline: 'ऑफलाइन',
      youSaid: 'तुम्ही म्हणालात',
      welcomeMessage: 'नमस्कार! मी न्याय साथी, तुमचा कायदेशीर मित्र. आज तुमच्या मनात काय आहे? तुमचे कायदेशीर हक्क समजून घेण्यास मदत करण्यासाठी मी इथे आहे.',
      thinking: 'विचार करत आहे...',
      processing: 'प्रक्रिया',
      transcribing: 'लिहित आहे',
      listen: 'ऐका',
      stop: 'थांबा',
      references: 'संदर्भ',
      newSessionStarted: 'नवीन सत्र सुरू झाले',
      newSessionDesc: 'तुमचे संभाषण साफ केले गेले',
      onboarding: {
        talkToMe: 'माझ्याशी बोला',
        talkToMeDesc: 'फक्त माइक टॅप करा आणि तुमचा प्रश्न विचारा. मित्राशी बोलता तसे नैसर्गिकपणे बोला!',
        switchToText: 'टेक्स्टवर स्विच करा',
        switchToTextDesc: 'टाइप करणे आवडते? खालच्या बारमध्ये स्विच वापरून टेक्स्ट मोडवर जा.',
        uploadDocs: 'दस्तऐवज अपलोड करा',
        uploadDocsDesc: 'AI विश्लेषणासाठी कायदेशीर दस्तऐवज अपलोड करा. आम्ही PDF, DOCX, XLSX, CSV आणि प्रतिमांना सपोर्ट करतो.',
        listenResponses: 'उत्तरे ऐका',
        listenResponsesDesc: 'तुमच्या भाषेत ऐकण्यासाठी कोणत्याही उत्तरावर स्पीकर आयकॉनवर क्लिक करा.',
        skip: 'वगळा',
        next: 'पुढे',
        getStarted: 'सुरू करा',
        stepOf: 'पाऊल {current} चे {total}',
      },
      consent: {
        byUsing: 'न्याय साथी वापरून, तुम्ही सहमत आहात:',
        shareLocation: 'संबंधित स्थानिक कायदेशीर सल्ल्यासाठी तुमचे स्थान शेअर करा',
        allowLogging: 'सुरक्षिततेसाठी अनामिक कनेक्शन लॉगिंगला परवानगी द्या',
        helpImprove: 'सुधारणा करण्यासाठी चॅटमधून शिकण्याची परवानगी द्या (सर्व डेटा अनामिक राहतो)',
        acceptTerms: 'अटी आणि गोपनीयता धोरण स्वीकारा',
        agreeToAll: 'मी वरील सर्वांशी सहमत आहे',
      },
      landing: {
        welcome: 'न्याय साथीमध्ये आपले स्वागत आहे',
        tagline: 'तुमच्या भाषेत त्वरित कायदेशीर प्रथमोपचार',
        selectLanguage: 'तुमची भाषा निवडा',
        trustedCompanion: 'तुमचा विश्वासू कायदेशीर प्रथमोपचार सोबती',
        back: 'मागे',
        letsChat: 'बोलूया',
        talkToUs: 'तुमच्या कायदेशीर प्रश्नांबद्दल आमच्याशी बोला',
      },
      about: {
        title: 'न्याय साथी बद्दल',
        back: 'मागे',
        missionTitle: 'भारतासाठी कायदेशीर ज्ञानाचे लोकशाहीकरण',
        missionDescription: 'न्याय साथी फक्त एक अॅप नाही—हे एक मिशन आहे. प्रत्येक भारतीयाला त्यांच्या स्वतःच्या भाषेत त्वरित, सुलभ आणि अचूक कायदेशीर मार्गदर्शन देण्यासाठी बनवले.',
        createdBy: 'वेंकट राम रेड्डी गानुतुला',
        creatorDescription: 'सामाजिक प्रभावाबद्दल उत्साही, भारतासाठी समाधान तयार करण्यावर विश्वास ठेवतात.',
        profile: 'प्रोफाइल',
        feature1Title: 'समावेशक तंत्रज्ञान',
        feature1Desc: '12+ भारतीय भाषांच्या समर्थनासह भाषा अडथळे तोडणे, प्रत्येक नागरिकाला कायदेशीर माहिती उपलब्ध करणे.',
        feature2Title: 'सशक्तीकरण',
        feature2Desc: 'गोंधळात टाकणारे कायदेशीर शब्द कोणालाही समजेल अशा सोप्या, कृतीयोग्य सल्ल्यात बदलणे.',
        feature3Title: 'सहानुभूतीने सेवा',
        feature3Desc: 'प्रथम ऐकणारा, तुमची परिस्थिती समजून घेणारा आणि काळजीने मार्गदर्शन करणारा AI सोबती.',
        footer: 'वेंकट राम रेड्डी गानुतुला यांनी भारतासाठी ❤️ ने बनवले',
      },
    },
  },
  GU: {
    code: 'GU',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    fontClass: 'font-gujarati',
    direction: 'ltr',
    ttsVoice: 'gu-IN-Wavenet-A',
    disclaimer: 'આ કાનૂની સલાહ નથી. ફક્ત સામાન્ય માહિતી.',
    ui: {
      startConsultation: 'કાનૂની સલાહ શરૂ કરો',
      tapToSpeak: 'બોલવા માટે ટૅપ કરો',
      listening: 'સાંભળી રહ્યો છું',
      analyzing: 'વિશ્લેષણ કરી રહ્યો છું',
      speaking: 'બોલી રહ્યો છું',
      uploadDocument: 'દસ્તાવેજ અપલોડ કરો',
      typeMessage: 'તમારો સંદેશ લખો...',
      send: 'મોકલો',
      emergency: 'કટોકટી',
      resources: 'સંસાધનો',
      info: 'માહિતી',
      admin: 'સંચાલક',
      startFresh: 'નવેસરથી શરૂ કરો',
      helpline: 'હેલ્પલાઇન',
      attach: 'જોડો',
      voice: 'અવાજ',
      text: 'ટેક્સ્ટ',
      connected: 'કનેક્ટેડ',
      offline: 'ઑફલાઇન',
      youSaid: 'તમે કહ્યું',
      welcomeMessage: 'નમસ્તે! હું ન્યાય સાથી, તમારો કાનૂની મિત્ર. આજે તમારા મનમાં શું છે? તમારા કાનૂની અધિકારો સમજવામાં મદદ કરવા હું અહીં છું.',
      thinking: 'વિચારી રહ્યો છું...',
      processing: 'પ્રોસેસિંગ',
      transcribing: 'લખી રહ્યો છું',
      listen: 'સાંભળો',
      stop: 'બંધ કરો',
      references: 'સંદર્ભો',
      newSessionStarted: 'નવું સત્ર શરૂ થયું',
      newSessionDesc: 'તમારી વાતચીત સાફ કરવામાં આવી',
      onboarding: {
        talkToMe: 'મારી સાથે વાત કરો',
        talkToMeDesc: 'બસ માઇક ટેપ કરો અને તમારો પ્રશ્ન પૂછો. મિત્ર સાથે વાત કરો તેમ કુદરતી રીતે બોલો!',
        switchToText: 'ટેક્સ્ટ પર સ્વિચ કરો',
        switchToTextDesc: 'ટાઇપ કરવાનું પસંદ છે? નીચેની બારમાં સ્વિચ વાપરીને ટેક્સ્ટ મોડ પર જાઓ.',
        uploadDocs: 'દસ્તાવેજો અપલોડ કરો',
        uploadDocsDesc: 'AI વિશ્લેષણ માટે કાનૂની દસ્તાવેજો અપલોડ કરો. અમે PDF, DOCX, XLSX, CSV અને છબીઓને સપોર્ટ કરીએ છીએ.',
        listenResponses: 'જવાબો સાંભળો',
        listenResponsesDesc: 'તમારી ભાષામાં સાંભળવા માટે કોઈપણ જવાબ પર સ્પીકર આયકન ક્લિક કરો.',
        skip: 'છોડો',
        next: 'આગળ',
        getStarted: 'શરૂ કરો',
        stepOf: 'પગલું {current} માંથી {total}',
      },
      consent: {
        byUsing: 'ન્યાય સાથી વાપરીને, તમે સંમત થાઓ છો:',
        shareLocation: 'સંબંધિત સ્થાનિક કાનૂની સલાહ માટે તમારું સ્થાન શેર કરો',
        allowLogging: 'સુરક્ષા માટે અનામી કનેક્શન લોગિંગની મંજૂરી આપો',
        helpImprove: 'સુધારણા માટે ચેટમાંથી શીખવા દો (બધો ડેટા અનામી રહે છે)',
        acceptTerms: 'શરતો અને ગોપનીયતા નીતિ સ્વીકારો',
        agreeToAll: 'હું ઉપરોક્ત બધા સાથે સંમત છું',
      },
      landing: {
        welcome: 'ન્યાય સાથીમાં આપનું સ્વાગત છે',
        tagline: 'તમારી ભાષામાં તાત્કાલિક કાનૂની પ્રાથમિક સારવાર',
        selectLanguage: 'તમારી ભાષા પસંદ કરો',
        trustedCompanion: 'તમારો વિશ્વસનીય કાનૂની પ્રાથમિક સારવાર સાથી',
        back: 'પાછળ',
        letsChat: 'વાત કરીએ',
        talkToUs: 'તમારા કાનૂની પ્રશ્નો વિશે અમારી સાથે વાત કરો',
      },
      about: {
        title: 'ન્યાય સાથી વિશે',
        back: 'પાછળ',
        missionTitle: 'ભારત માટે કાનૂની જ્ઞાનનું લોકશાહીકરણ',
        missionDescription: 'ન્યાય સાથી માત્ર એક એપ નથી—તે એક મિશન છે. દરેક ભારતીયને તેમની પોતાની ભાષામાં તાત્કાલિક, સુલભ અને સચોટ કાનૂની માર્ગદર્શન આપવા માટે બનાવેલ.',
        createdBy: 'વેંકટ રામ રેડ્ડી ગાનુતુલા',
        creatorDescription: 'સામાજિક પ્રભાવ માટે ઉત્સાહી, ભારત માટે સોલ્યુશન્સ બનાવવામાં વિશ્વાસ રાખે છે.',
        profile: 'પ્રોફાઇલ',
        feature1Title: 'સમાવેશક ટેક્નોલોજી',
        feature1Desc: '12+ ભારતીય ભાષાઓના સમર્થન સાથે ભાષા અવરોધો તોડીને, દરેક નાગરિક માટે કાનૂની માહિતી સુલભ બનાવે છે.',
        feature2Title: 'સશક્તિકરણ',
        feature2Desc: 'ગૂંચવણભરી કાનૂની ભાષાને કોઈપણ સમજી શકે તેવી સરળ, ક્રિયાશીલ સલાહમાં ફેરવે છે.',
        feature3Title: 'સહાનુભૂતિ સાથે સેવા',
        feature3Desc: 'પહેલા સાંભળનાર, તમારી પરિસ્થિતિ સમજનાર અને કાળજી સાથે માર્ગદર્શન આપનાર AI સાથી.',
        footer: 'વેંકટ રામ રેડ્ડી ગાનુતુલા દ્વારા ભારત માટે ❤️ થી બનાવેલ',
      },
    },
  },
  KN: {
    code: 'KN',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    fontClass: 'font-kannada',
    direction: 'ltr',
    ttsVoice: 'kn-IN-Wavenet-A',
    disclaimer: 'ಇದು ಕಾನೂನು ಸಲಹೆ ಅಲ್ಲ. ಸಾಮಾನ್ಯ ಮಾಹಿತಿ ಮಾತ್ರ.',
    ui: {
      startConsultation: 'ಕಾನೂನು ಸಮಾಲೋಚನೆ ಪ್ರಾರಂಭಿಸಿ',
      tapToSpeak: 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
      listening: 'ಕೇಳುತ್ತಿದ್ದೇನೆ',
      analyzing: 'ವಿಶ್ಲೇಷಿಸುತ್ತಿದ್ದೇನೆ',
      speaking: 'ಮಾತನಾಡುತ್ತಿದ್ದೇನೆ',
      uploadDocument: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      typeMessage: 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
      send: 'ಕಳುಹಿಸಿ',
      emergency: 'ತುರ್ತು',
      resources: 'ಸಂಪನ್ಮೂಲಗಳು',
      info: 'ಮಾಹಿತಿ',
      admin: 'ನಿರ್ವಾಹಕ',
      startFresh: 'ಹೊಸದಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
      helpline: 'ಹೆಲ್ಪ್‌ಲೈನ್',
      attach: 'ಲಗತ್ತಿಸಿ',
      voice: 'ಧ್ವನಿ',
      text: 'ಪಠ್ಯ',
      connected: 'ಸಂಪರ್ಕಿತ',
      offline: 'ಆಫ್‌ಲೈನ್',
      youSaid: 'ನೀವು ಹೇಳಿದ್ದು',
      welcomeMessage: 'ನಮಸ್ಕಾರ! ನಾನು ನ್ಯಾಯ ಸಾಥಿ, ನಿಮ್ಮ ಕಾನೂನು ಸ್ನೇಹಿತ. ಇಂದು ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿ ಏನಿದೆ? ನಿಮ್ಮ ಕಾನೂನು ಹಕ್ಕುಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡಲು ನಾನು ಇಲ್ಲಿದ್ದೇನೆ.',
      thinking: 'ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ...',
      processing: 'ಪ್ರಕ್ರಿಯೆ',
      transcribing: 'ಬರೆಯುತ್ತಿದ್ದೇನೆ',
      listen: 'ಕೇಳಿ',
      stop: 'ನಿಲ್ಲಿಸಿ',
      references: 'ಉಲ್ಲೇಖಗಳು',
      newSessionStarted: 'ಹೊಸ ಸೆಷನ್ ಪ್ರಾರಂಭವಾಯಿತು',
      newSessionDesc: 'ನಿಮ್ಮ ಸಂಭಾಷಣೆ ತೆರವುಗೊಳಿಸಲಾಗಿದೆ',
      onboarding: {
        talkToMe: 'ನನ್ನೊಂದಿಗೆ ಮಾತನಾಡಿ',
        talkToMeDesc: 'ಮೈಕ್ ಟ್ಯಾಪ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಕೇಳಿ. ಸ್ನೇಹಿತರೊಂದಿಗೆ ಮಾತನಾಡುವಂತೆ ಸಹಜವಾಗಿ ಮಾತನಾಡಿ!',
        switchToText: 'ಟೆಕ್ಸ್ಟ್ ಗೆ ಬದಲಿಸಿ',
        switchToTextDesc: 'ಟೈಪ್ ಮಾಡಲು ಇಷ್ಟಪಡುತ್ತೀರಾ? ಕೆಳಗಿನ ಬಾರ್‌ನಲ್ಲಿ ಸ್ವಿಚ್ ಬಳಸಿ ಟೆಕ್ಸ್ಟ್ ಮೋಡ್‌ಗೆ ಹೋಗಿ.',
        uploadDocs: 'ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
        uploadDocsDesc: 'AI ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ನಾವು PDF, DOCX, XLSX, CSV ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ಬೆಂಬಲಿಸುತ್ತೇವೆ.',
        listenResponses: 'ಉತ್ತರಗಳನ್ನು ಕೇಳಿ',
        listenResponsesDesc: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಕೇಳಲು ಯಾವುದೇ ಉತ್ತರದ ಮೇಲೆ ಸ್ಪೀಕರ್ ಐಕಾನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.',
        skip: 'ಬಿಟ್ಟುಬಿಡಿ',
        next: 'ಮುಂದೆ',
        getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
        stepOf: 'ಹಂತ {current} ರಲ್ಲಿ {total}',
      },
      consent: {
        byUsing: 'ನ್ಯಾಯ ಸಾಥಿ ಬಳಸುವ ಮೂಲಕ, ನೀವು ಒಪ್ಪುತ್ತೀರಿ:',
        shareLocation: 'ಸಂಬಂಧಿತ ಸ್ಥಳೀಯ ಕಾನೂನು ಸಲಹೆಗಾಗಿ ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
        allowLogging: 'ಭದ್ರತೆಗಾಗಿ ಅನಾಮಧೇಯ ಸಂಪರ್ಕ ಲಾಗಿಂಗ್ ಅನ್ನು ಅನುಮತಿಸಿ',
        helpImprove: 'ಸುಧಾರಣೆಗಾಗಿ ಚಾಟ್‌ಗಳಿಂದ ಕಲಿಯಲು ಅವಕಾಶ ಕೊಡಿ (ಎಲ್ಲಾ ಡೇಟಾ ಅನಾಮಧೇಯವಾಗಿರುತ್ತದೆ)',
        acceptTerms: 'ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತೆ ನೀತಿಯನ್ನು ಸ್ವೀಕರಿಸಿ',
        agreeToAll: 'ಮೇಲಿನ ಎಲ್ಲದಕ್ಕೂ ನಾನು ಒಪ್ಪುತ್ತೇನೆ',
      },
      landing: {
        welcome: 'ನ್ಯಾಯ ಸಾಥಿಗೆ ಸ್ವಾಗತ',
        tagline: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ತತ್‌ಕ್ಷಣ ಕಾನೂನು ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ',
        selectLanguage: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
        trustedCompanion: 'ನಿಮ್ಮ ನಂಬಿಕಸ್ಥ ಕಾನೂನು ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ಸಂಗಾತಿ',
        back: 'ಹಿಂದೆ',
        letsChat: 'ಮಾತನಾಡೋಣ',
        talkToUs: 'ನಿಮ್ಮ ಕಾನೂನು ಪ್ರಶ್ನೆಗಳ ಬಗ್ಗೆ ನಮ್ಮೊಂದಿಗೆ ಮಾತನಾಡಿ',
      },
      about: {
        title: 'ನ್ಯಾಯ ಸಾಥಿ ಬಗ್ಗೆ',
        back: 'ಹಿಂದೆ',
        missionTitle: 'ಭಾರತಕ್ಕಾಗಿ ಕಾನೂನು ಜ್ಞಾನದ ಪ್ರಜಾಪ್ರಭುತ್ವೀಕರಣ',
        missionDescription: 'ನ್ಯಾಯ ಸಾಥಿ ಕೇವಲ ಆ್ಯಪ್ ಅಲ್ಲ—ಇದು ಒಂದು ಮಿಷನ್. ಪ್ರತಿ ಭಾರತೀಯರಿಗೆ ಅವರ ಸ್ವಂತ ಭಾಷೆಯಲ್ಲಿ ತತ್‌ಕ್ಷಣ, ಲಭ್ಯವಾಗುವ, ನಿಖರ ಕಾನೂನು ಮಾರ್ಗದರ್ಶನ ನೀಡಲು ನಿರ್ಮಿಸಲಾಗಿದೆ.',
        createdBy: 'ವೆಂಕಟ್ ರಾಮ್ ರೆಡ್ಡಿ ಗಾನುತುಲ',
        creatorDescription: 'ಸಾಮಾಜಿಕ ಪರಿಣಾಮದ ಬಗ್ಗೆ ಉತ್ಸಾಹ ಮತ್ತು "ಭಾರತಕ್ಕಾಗಿ ಪರಿಹಾರಗಳು" ದೃಷ್ಟಿಯಿಂದ ಪ್ರೇರಿತರಾಗಿ, ವೆಂಕಟ್ ಆರ್ಥಿಕ ಅಂತರವನ್ನು ಸೇತುವೆ ಮಾಡಲು ಮತ್ತು ಸಾಮಾನ್ಯ ಭಾರತೀಯರನ್ನು ಸಬಲೀಕರಿಸಲು ನ್ಯಾಯ ಸಾಥಿಯನ್ನು ರಚಿಸಿದರು.',
        profile: 'ಪ್ರೊಫೈಲ್',
        feature1Title: 'ಸಮಗ್ರ ತಂತ್ರಜ್ಞಾನ',
        feature1Desc: '12+ ಭಾರತೀಯ ಭಾಷೆಗಳ ಬೆಂಬಲದೊಂದಿಗೆ ಭಾಷಾ ತಡೆಗಳನ್ನು ಮುರಿದು, ಪ್ರತಿ ನಾಗರಿಕರಿಗೆ ಕಾನೂನು ಮಾಹಿತಿಯನ್ನು ಲಭ್ಯವಾಗಿಸುವುದು.',
        feature2Title: 'ಸಬಲೀಕರಣ',
        feature2Desc: 'ಗೊಂದಲಮಯ ಕಾನೂನು ಪದಗಳನ್ನು ಯಾರಾದರೂ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಬಹುದಾದ ಸರಳ, ಕ್ರಿಯಾಶೀಲ ಸಲಹೆಯಾಗಿ ಪರಿವರ್ತಿಸುವುದು.',
        feature3Title: 'ಸಹಾನುಭೂತಿಯಿಂದ ಸೇವೆ',
        feature3Desc: 'ಮೊದಲು ಆಲಿಸುವ, ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವ, ಕಾಳಜಿಯಿಂದ ಮಾರ್ಗದರ್ಶನ ಮಾಡುವ AI ಸಂಗಾತಿ.',
        footer: 'ವೆಂಕಟ್ ರಾಮ್ ರೆಡ್ಡಿ ಗಾನುತುಲ ❤️ ನಿಂದ ಭಾರತಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ',
      },
    },
  },
  ML: {
    code: 'ML',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    fontClass: 'font-malayalam',
    direction: 'ltr',
    ttsVoice: 'ml-IN-Wavenet-A',
    disclaimer: 'ഇത് നിയമ ഉപദേശമല്ല. പൊതു വിവരങ്ങൾ മാത്രം.',
    ui: {
      startConsultation: 'നിയമ കൺസൾട്ടേഷൻ ആരംഭിക്കുക',
      tapToSpeak: 'സംസാരിക്കാൻ ടാപ്പ് ചെയ്യുക',
      listening: 'കേൾക്കുന്നു',
      analyzing: 'വിശകലനം ചെയ്യുന്നു',
      speaking: 'സംസാരിക്കുന്നു',
      uploadDocument: 'രേഖ അപ്‌ലോഡ് ചെയ്യുക',
      typeMessage: 'നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
      send: 'അയയ്ക്കുക',
      emergency: 'അടിയന്തരം',
      resources: 'വിഭവങ്ങൾ',
      info: 'വിവരങ്ങൾ',
      admin: 'അഡ്മിൻ',
      startFresh: 'പുതുതായി തുടങ്ങുക',
      helpline: 'ഹെൽപ്പ്‌ലൈൻ',
      attach: 'അറ്റാച്ച് ചെയ്യുക',
      voice: 'ശബ്ദം',
      text: 'ടെക്സ്റ്റ്',
      connected: 'കണക്റ്റഡ്',
      offline: 'ഓഫ്‌ലൈൻ',
      youSaid: 'നിങ്ങൾ പറഞ്ഞത്',
      welcomeMessage: 'ഹലോ! ഞാൻ ന്യായ സാഥി, നിങ്ങളുടെ നിയമ സുഹൃത്ത്. ഇന്ന് നിങ്ങളുടെ മനസ്സിൽ എന്താണ്? നിങ്ങളുടെ നിയമ അവകാശങ്ങൾ മനസ്സിലാക്കാൻ സഹായിക്കാൻ ഞാൻ ഇവിടെയുണ്ട്.',
      thinking: 'ചിന്തിക്കുന്നു...',
      processing: 'പ്രോസസ്സിംഗ്',
      transcribing: 'എഴുതുന്നു',
      listen: 'കേൾക്കുക',
      stop: 'നിർത്തുക',
      references: 'റഫറൻസുകൾ',
      newSessionStarted: 'പുതിയ സെഷൻ ആരംഭിച്ചു',
      newSessionDesc: 'നിങ്ങളുടെ സംഭാഷണം മായ്ച്ചു',
      onboarding: {
        talkToMe: 'എന്നോട് സംസാരിക്കൂ',
        talkToMeDesc: 'മൈക്ക് ടാപ്പ് ചെയ്ത് നിങ്ങളുടെ ചോദ്യം ചോദിക്കൂ. ഒരു സുഹൃത്തിനോട് സംസാരിക്കുന്നത് പോലെ സ്വാഭാവികമായി സംസാരിക്കൂ!',
        switchToText: 'ടെക്സ്റ്റിലേക്ക് മാറുക',
        switchToTextDesc: 'ടൈപ്പ് ചെയ്യാൻ ഇഷ്ടപ്പെടുന്നോ? താഴെയുള്ള ബാറിലെ സ്വിച്ച് ഉപയോഗിച്ച് ടെക്സ്റ്റ് മോഡിലേക്ക് മാറുക.',
        uploadDocs: 'ഡോക്യുമെന്റുകൾ അപ്‌ലോഡ് ചെയ്യുക',
        uploadDocsDesc: 'AI വിശകലനത്തിനായി നിയമ ഡോക്യുമെന്റുകൾ അപ്‌ലോഡ് ചെയ്യുക. ഞങ്ങൾ PDF, DOCX, XLSX, CSV, ചിത്രങ്ങൾ എന്നിവ പിന്തുണയ്ക്കുന്നു.',
        listenResponses: 'മറുപടികൾ കേൾക്കുക',
        listenResponsesDesc: 'നിങ്ങളുടെ ഭാഷയിൽ കേൾക്കാൻ ഏതെങ്കിലും മറുപടിയിൽ സ്പീക്കർ ഐക്കണിൽ ക്ലിക്ക് ചെയ്യുക.',
        skip: 'ഒഴിവാക്കുക',
        next: 'അടുത്തത്',
        getStarted: 'ആരംഭിക്കുക',
        stepOf: 'ഘട്ടം {current} ൽ {total}',
      },
      consent: {
        byUsing: 'ന്യായ സാഥി ഉപയോഗിക്കുന്നതിലൂടെ, നിങ്ങൾ സമ്മതിക്കുന്നു:',
        shareLocation: 'പ്രസക്തമായ പ്രാദേശിക നിയമ ഉപദേശത്തിനായി നിങ്ങളുടെ ലൊക്കേഷൻ പങ്കിടുക',
        allowLogging: 'സുരക്ഷയ്ക്കായി അജ്ഞാത കണക്ഷൻ ലോഗിംഗ് അനുവദിക്കുക',
        helpImprove: 'മെച്ചപ്പെടുത്തുന്നതിനായി ചാറ്റുകളിൽ നിന്ന് പഠിക്കാൻ അനുവദിക്കുക (എല്ലാ ഡാറ്റയും അജ്ഞാതമായി തുടരും)',
        acceptTerms: 'നിബന്ധനകളും സ്വകാര്യതാ നയവും സ്വീകരിക്കുക',
        agreeToAll: 'മുകളിലുള്ള എല്ലാത്തിനും ഞാൻ സമ്മതിക്കുന്നു',
      },
      landing: {
        welcome: 'ന്യായ സാഥിയിലേക്ക് സ്വാഗതം',
        tagline: 'നിങ്ങളുടെ ഭാഷയിൽ തൽക്ഷണ നിയമ പ്രഥമശുശ്രൂഷ',
        selectLanguage: 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
        trustedCompanion: 'നിങ്ങളുടെ വിശ്വസ്ത നിയമ പ്രഥമശുശ്രൂഷ സഹചാരി',
        back: 'പിന്നോട്ട്',
        letsChat: 'സംസാരിക്കാം',
        talkToUs: 'നിങ്ങളുടെ നിയമ ചോദ്യങ്ങളെക്കുറിച്ച് ഞങ്ങളോട് സംസാരിക്കുക',
      },
      about: {
        title: 'ന്യായ സാഥിയെക്കുറിച്ച്',
        back: 'പിന്നോട്ട്',
        missionTitle: 'ഭാരതത്തിനായി നിയമ അറിവിന്റെ ജനാധിപത്യവൽക്കരണം',
        missionDescription: 'ന്യായ സാഥി വെറും ആപ്പ് അല്ല—ഇത് ഒരു ദൗത്യമാണ്. ഓരോ ഇന്ത്യക്കാരനും അവരുടെ സ്വന്തം ഭാഷയിൽ തൽക്ഷണ, ലഭ്യമായ, കൃത്യമായ നിയമ മാർഗ്ഗനിർദ്ദേശം നൽകാൻ നിർമ്മിച്ചത്.',
        createdBy: 'വെങ്കട് രാം റെഡ്ഡി ഗാനുതുല',
        creatorDescription: 'സാമൂഹിക സ്വാധീനത്തോടുള്ള അഭിനിവേശവും "ഭാരതത്തിനായി പരിഹാരങ്ങൾ" എന്ന കാഴ്ചപ്പാടും പ്രചോദനമായി, സാമ്പത്തിക അന്തരം നികത്താനും സാധാരണ ഇന്ത്യക്കാരെ ശാക്തീകരിക്കാനും വെങ്കട് ന്യായ സാഥി സൃഷ്ടിച്ചു.',
        profile: 'പ്രൊഫൈൽ',
        feature1Title: 'സമഗ്ര സാങ്കേതികവിദ്യ',
        feature1Desc: '12+ ഇന്ത്യൻ ഭാഷകളുടെ പിന്തുണയോടെ ഭാഷാ തടസ്സങ്ങൾ തകർത്ത്, എല്ലാ പൗരന്മാർക്കും നിയമ വിവരങ്ങൾ ലഭ്യമാക്കുന്നു.',
        feature2Title: 'ശാക്തീകരണം',
        feature2Desc: 'ആശയക്കുഴപ്പമുണ്ടാക്കുന്ന നിയമ പദങ്ങളെ ആർക്കും മനസ്സിലാക്കാൻ കഴിയുന്ന ലളിതമായ, പ്രവർത്തനക്ഷമമായ ഉപദേശമാക്കി മാറ്റുന്നു.',
        feature3Title: 'സഹാനുഭൂതിയോടെ സേവനം',
        feature3Desc: 'ആദ്യം കേൾക്കുന്ന, നിങ്ങളുടെ സാഹചര്യം മനസ്സിലാക്കുന്ന, കരുതലോടെ മാർഗ്ഗനിർദ്ദേശം നൽകുന്ന AI സഹചാരി.',
        footer: 'വെങ്കട് രാം റെഡ്ഡി ഗാനുതുല ❤️ ഭാരതത്തിനായി നിർമ്മിച്ചത്',
      },
    },
  },
  PA: {
    code: 'PA',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    fontClass: 'font-punjabi',
    direction: 'ltr',
    ttsVoice: 'pa-IN-Wavenet-A',
    disclaimer: 'ਇਹ ਕਾਨੂੰਨੀ ਸਲਾਹ ਨਹੀਂ ਹੈ। ਸਿਰਫ਼ ਆਮ ਜਾਣਕਾਰੀ।',
    ui: {
      startConsultation: 'ਕਾਨੂੰਨੀ ਸਲਾਹ ਸ਼ੁਰੂ ਕਰੋ',
      tapToSpeak: 'ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ',
      listening: 'ਸੁਣ ਰਿਹਾ ਹਾਂ',
      analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹਾਂ',
      speaking: 'ਬੋਲ ਰਿਹਾ ਹਾਂ',
      uploadDocument: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
      typeMessage: 'ਆਪਣਾ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...',
      send: 'ਭੇਜੋ',
      emergency: 'ਐਮਰਜੈਂਸੀ',
      resources: 'ਸਰੋਤ',
      info: 'ਜਾਣਕਾਰੀ',
      admin: 'ਪ੍ਰਬੰਧਕ',
      startFresh: 'ਨਵੇਂ ਸਿਰੇ ਤੋਂ ਸ਼ੁਰੂ ਕਰੋ',
      helpline: 'ਹੈਲਪਲਾਈਨ',
      attach: 'ਜੋੜੋ',
      voice: 'ਆਵਾਜ਼',
      text: 'ਟੈਕਸਟ',
      connected: 'ਕਨੈਕਟ',
      offline: 'ਆਫ਼ਲਾਈਨ',
      youSaid: 'ਤੁਸੀਂ ਕਿਹਾ',
      welcomeMessage: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਨਿਆਂ ਸਾਥੀ ਹਾਂ, ਤੁਹਾਡਾ ਕਾਨੂੰਨੀ ਦੋਸਤ। ਅੱਜ ਤੁਹਾਡੇ ਮਨ ਵਿੱਚ ਕੀ ਹੈ? ਮੈਂ ਤੁਹਾਡੇ ਕਾਨੂੰਨੀ ਹੱਕਾਂ ਨੂੰ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰਨ ਲਈ ਇੱਥੇ ਹਾਂ।',
      thinking: 'ਸੋਚ ਰਿਹਾ ਹਾਂ...',
      processing: 'ਪ੍ਰੋਸੈਸਿੰਗ',
      transcribing: 'ਲਿਖ ਰਿਹਾ ਹਾਂ',
      listen: 'ਸੁਣੋ',
      stop: 'ਰੋਕੋ',
      references: 'ਹਵਾਲੇ',
      newSessionStarted: 'ਨਵਾਂ ਸੈਸ਼ਨ ਸ਼ੁਰੂ ਹੋਇਆ',
      newSessionDesc: 'ਤੁਹਾਡੀ ਗੱਲਬਾਤ ਸਾਫ਼ ਕੀਤੀ ਗਈ',
      onboarding: {
        talkToMe: 'ਮੇਰੇ ਨਾਲ ਗੱਲ ਕਰੋ',
        talkToMeDesc: 'ਬੱਸ ਮਾਈਕ ਟੈਪ ਕਰੋ ਅਤੇ ਆਪਣਾ ਸਵਾਲ ਪੁੱਛੋ। ਦੋਸਤ ਨਾਲ ਗੱਲ ਕਰਦੇ ਹੋ ਜਿਵੇਂ ਕੁਦਰਤੀ ਤੌਰ ਤੇ ਬੋਲੋ!',
        switchToText: 'ਟੈਕਸਟ ਤੇ ਜਾਓ',
        switchToTextDesc: 'ਟਾਈਪ ਕਰਨਾ ਪਸੰਦ ਹੈ? ਹੇਠਲੀ ਬਾਰ ਵਿੱਚ ਸਵਿੱਚ ਵਰਤ ਕੇ ਟੈਕਸਟ ਮੋਡ ਤੇ ਜਾਓ।',
        uploadDocs: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
        uploadDocsDesc: 'AI ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਕਾਨੂੰਨੀ ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ। ਅਸੀਂ PDF, DOCX, XLSX, CSV ਅਤੇ ਤਸਵੀਰਾਂ ਦਾ ਸਮਰਥਨ ਕਰਦੇ ਹਾਂ।',
        listenResponses: 'ਜਵਾਬ ਸੁਣੋ',
        listenResponsesDesc: 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸੁਣਨ ਲਈ ਕਿਸੇ ਵੀ ਜਵਾਬ ਤੇ ਸਪੀਕਰ ਆਈਕਨ ਕਲਿੱਕ ਕਰੋ।',
        skip: 'ਛੱਡੋ',
        next: 'ਅਗਲਾ',
        getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
        stepOf: 'ਕਦਮ {current} ਵਿੱਚੋਂ {total}',
      },
      consent: {
        byUsing: 'ਨਿਆਂ ਸਾਥੀ ਵਰਤ ਕੇ, ਤੁਸੀਂ ਸਹਿਮਤ ਹੋ:',
        shareLocation: 'ਸੰਬੰਧਿਤ ਸਥਾਨਕ ਕਾਨੂੰਨੀ ਸਲਾਹ ਲਈ ਆਪਣਾ ਸਥਾਨ ਸਾਂਝਾ ਕਰੋ',
        allowLogging: 'ਸੁਰੱਖਿਆ ਲਈ ਅਗਿਆਤ ਕਨੈਕਸ਼ਨ ਲੌਗਿੰਗ ਦੀ ਆਗਿਆ ਦਿਓ',
        helpImprove: 'ਸੁਧਾਰ ਲਈ ਚੈਟਾਂ ਤੋਂ ਸਿੱਖਣ ਦਿਓ (ਸਾਰਾ ਡਾਟਾ ਅਗਿਆਤ ਰਹਿੰਦਾ ਹੈ)',
        acceptTerms: 'ਸ਼ਰਤਾਂ ਅਤੇ ਗੋਪਨੀਯਤਾ ਨੀਤੀ ਸਵੀਕਾਰ ਕਰੋ',
        agreeToAll: 'ਮੈਂ ਉਪਰੋਕਤ ਸਾਰਿਆਂ ਨਾਲ ਸਹਿਮਤ ਹਾਂ',
      },
      landing: {
        welcome: 'ਨਿਆਂ ਸਾਥੀ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ',
        tagline: 'ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਤੁਰੰਤ ਕਾਨੂੰਨੀ ਮੁੱਢਲੀ ਸਹਾਇਤਾ',
        selectLanguage: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
        trustedCompanion: 'ਤੁਹਾਡਾ ਭਰੋਸੇਮੰਦ ਕਾਨੂੰਨੀ ਮੁੱਢਲੀ ਸਹਾਇਤਾ ਸਾਥੀ',
        back: 'ਪਿੱਛੇ',
        letsChat: 'ਗੱਲ ਕਰੀਏ',
        talkToUs: 'ਆਪਣੇ ਕਾਨੂੰਨੀ ਸਵਾਲਾਂ ਬਾਰੇ ਸਾਡੇ ਨਾਲ ਗੱਲ ਕਰੋ',
      },
      about: {
        title: 'ਨਿਆਂ ਸਾਥੀ ਬਾਰੇ',
        back: 'ਪਿੱਛੇ',
        missionTitle: 'ਭਾਰਤ ਲਈ ਕਾਨੂੰਨੀ ਗਿਆਨ ਦਾ ਲੋਕਤੰਤਰੀਕਰਨ',
        missionDescription: 'ਨਿਆਂ ਸਾਥੀ ਸਿਰਫ਼ ਇੱਕ ਐਪ ਨਹੀਂ ਹੈ—ਇਹ ਇੱਕ ਮਿਸ਼ਨ ਹੈ। ਹਰ ਭਾਰਤੀ ਨੂੰ ਉਨ੍ਹਾਂ ਦੀ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਤੁਰੰਤ, ਪਹੁੰਚਯੋਗ ਅਤੇ ਸਹੀ ਕਾਨੂੰਨੀ ਮਾਰਗਦਰਸ਼ਨ ਦੇਣ ਲਈ ਬਣਾਇਆ ਗਿਆ।',
        createdBy: 'ਵੈਂਕਟ ਰਾਮ ਰੈੱਡੀ ਗਾਨੁਤੁਲਾ',
        creatorDescription: 'ਸਮਾਜਿਕ ਪ੍ਰਭਾਵ ਲਈ ਜਨੂੰਨ ਅਤੇ "ਭਾਰਤ ਲਈ ਹੱਲ" ਦ੍ਰਿਸ਼ਟੀ ਨਾਲ ਪ੍ਰੇਰਿਤ, ਵੈਂਕਟ ਨੇ ਆਰਥਿਕ ਪਾੜੇ ਨੂੰ ਪੂਰਾ ਕਰਨ ਅਤੇ ਆਮ ਭਾਰਤੀਆਂ ਨੂੰ ਸਸ਼ਕਤ ਕਰਨ ਲਈ ਨਿਆਂ ਸਾਥੀ ਬਣਾਇਆ।',
        profile: 'ਪ੍ਰੋਫਾਈਲ',
        feature1Title: 'ਸਮਾਵੇਸ਼ੀ ਟੈਕਨੋਲੋਜੀ',
        feature1Desc: '12+ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਦੇ ਸਮਰਥਨ ਨਾਲ ਭਾਸ਼ਾ ਦੀਆਂ ਰੁਕਾਵਟਾਂ ਤੋੜਦਿਆਂ, ਹਰ ਨਾਗਰਿਕ ਲਈ ਕਾਨੂੰਨੀ ਜਾਣਕਾਰੀ ਪਹੁੰਚਯੋਗ ਬਣਾਉਣਾ।',
        feature2Title: 'ਸਸ਼ਕਤੀਕਰਨ',
        feature2Desc: 'ਗੁੰਝਲਦਾਰ ਕਾਨੂੰਨੀ ਸ਼ਬਦਾਵਲੀ ਨੂੰ ਸਰਲ, ਕਾਰਵਾਈਯੋਗ ਸਲਾਹ ਵਿੱਚ ਬਦਲਣਾ ਜੋ ਕੋਈ ਵੀ ਸਮਝ ਸਕੇ।',
        feature3Title: 'ਹਮਦਰਦੀ ਨਾਲ ਸੇਵਾ',
        feature3Desc: 'ਪਹਿਲਾਂ ਸੁਣਨ ਵਾਲਾ, ਤੁਹਾਡੀ ਸਥਿਤੀ ਸਮਝਣ ਵਾਲਾ, ਦੇਖਭਾਲ ਨਾਲ ਮਾਰਗਦਰਸ਼ਨ ਕਰਨ ਵਾਲਾ AI ਸਾਥੀ।',
        footer: 'ਵੈਂਕਟ ਰਾਮ ਰੈੱਡੀ ਗਾਨੁਤੁਲਾ ❤️ ਨਾਲ ਭਾਰਤ ਲਈ ਬਣਾਇਆ',
      },
    },
  },
  OR: {
    code: 'OR',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    fontClass: 'font-odia',
    direction: 'ltr',
    ttsVoice: 'or-IN-Standard-A',
    disclaimer: 'ଏହା ଆଇନଗତ ପରାମର୍ଶ ନୁହେଁ। କେବଳ ସାଧାରଣ ସୂଚନା।',
    ui: {
      startConsultation: 'ଆଇନଗତ ପରାମର୍ଶ ଆରମ୍ଭ କରନ୍ତୁ',
      tapToSpeak: 'କହିବାକୁ ଟ୍ୟାପ୍ କରନ୍ତୁ',
      listening: 'ଶୁଣୁଛି',
      analyzing: 'ବିଶ୍ଲେଷଣ କରୁଛି',
      speaking: 'କହୁଛି',
      uploadDocument: 'ଡକ୍ୟୁମେଣ୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
      typeMessage: 'ଆପଣଙ୍କ ସନ୍ଦେଶ ଟାଇପ୍ କରନ୍ତୁ...',
      send: 'ପଠାନ୍ତୁ',
      emergency: 'ଜରୁରୀ',
      resources: 'ସମ୍ବଳ',
      info: 'ସୂଚନା',
      admin: 'ପ୍ରଶାସକ',
      startFresh: 'ନୂଆରୁ ଆରମ୍ଭ କରନ୍ତୁ',
      helpline: 'ହେଲ୍ପଲାଇନ୍',
      attach: 'ସଂଲଗ୍ନ କରନ୍ତୁ',
      voice: 'ସ୍ୱର',
      text: 'ଟେକ୍ସଟ୍',
      connected: 'ସଂଯୁକ୍ତ',
      offline: 'ଅଫଲାଇନ୍',
      youSaid: 'ଆପଣ କହିଲେ',
      welcomeMessage: 'ନମସ୍କାର! ମୁଁ ନ୍ୟାୟ ସାଥୀ, ଆପଣଙ୍କ ଆଇନଗତ ସାଙ୍ଗ। ଆଜି ଆପଣଙ୍କ ମନରେ କଣ ଅଛି? ଆପଣଙ୍କ ଆଇନଗତ ଅଧିକାର ବୁଝିବାରେ ସାହାଯ୍ୟ କରିବାକୁ ମୁଁ ଏଠାରେ ଅଛି।',
      thinking: 'ଭାବୁଛି...',
      processing: 'ପ୍ରକ୍ରିୟାକରଣ',
      transcribing: 'ଲେଖୁଛି',
      listen: 'ଶୁଣନ୍ତୁ',
      stop: 'ବନ୍ଦ କରନ୍ତୁ',
      references: 'ସନ୍ଦର୍ଭ',
      newSessionStarted: 'ନୂଆ ସେସନ୍ ଆରମ୍ଭ ହେଲା',
      newSessionDesc: 'ଆପଣଙ୍କ କଥୋପକଥନ ସଫା ହୋଇଗଲା',
      onboarding: {
        talkToMe: 'ମୋ ସହ କଥା ହୁଅନ୍ତୁ',
        talkToMeDesc: 'ବସ୍ ମାଇକ୍ ଟ୍ୟାପ୍ କରନ୍ତୁ ଏବଂ ଆପଣଙ୍କ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ। ବନ୍ଧୁଙ୍କ ସହ କଥା ହେଉଥିବା ପରି ସ୍ୱାଭାବିକ ଭାବରେ କୁହନ୍ତୁ!',
        switchToText: 'ଟେକ୍ସଟ୍ କୁ ବଦଳାନ୍ତୁ',
        switchToTextDesc: 'ଟାଇପ୍ କରିବାକୁ ପସନ୍ଦ କରନ୍ତି? ତଳ ବାର୍‌ରେ ସ୍ୱିଚ୍ ବ୍ୟବହାର କରି ଟେକ୍ସଟ୍ ମୋଡ୍‌କୁ ଯାଆନ୍ତୁ।',
        uploadDocs: 'ଡକ୍ୟୁମେଣ୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
        uploadDocsDesc: 'AI ବିଶ୍ଲେଷଣ ପାଇଁ ଆଇନଗତ ଡକ୍ୟୁମେଣ୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ। ଆମେ PDF, DOCX, XLSX, CSV ଏବଂ ଚିତ୍ର ସମର୍ଥନ କରୁ।',
        listenResponses: 'ଉତ୍ତର ଶୁଣନ୍ତୁ',
        listenResponsesDesc: 'ଆପଣଙ୍କ ଭାଷାରେ ଶୁଣିବାକୁ ଯେକୌଣସି ଉତ୍ତରରେ ସ୍ପିକର୍ ଆଇକନ୍ କ୍ଲିକ୍ କରନ୍ତୁ।',
        skip: 'ଛାଡ଼ନ୍ତୁ',
        next: 'ପରବର୍ତ୍ତୀ',
        getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ',
        stepOf: 'ପାଦ {current} ର {total}',
      },
      consent: {
        byUsing: 'ନ୍ୟାୟ ସାଥୀ ବ୍ୟବହାର କରି, ଆପଣ ସହମତ ହେଉଛନ୍ତି:',
        shareLocation: 'ସମ୍ପୃକ୍ତ ସ୍ଥାନୀୟ ଆଇନଗତ ପରାମର୍ଶ ପାଇଁ ଆପଣଙ୍କ ଅବସ୍ଥାନ ସେୟାର କରନ୍ତୁ',
        allowLogging: 'ସୁରକ୍ଷା ପାଇଁ ଅଜ୍ଞାତ ସଂଯୋଗ ଲଗିଂ ର ଅନୁମତି ଦିଅନ୍ତୁ',
        helpImprove: 'ଉନ୍ନତି ପାଇଁ ଚାଟ୍ ରୁ ଶିଖିବାକୁ ଦିଅନ୍ତୁ (ସମସ୍ତ ଡାଟା ଅଜ୍ଞାତ ରହେ)',
        acceptTerms: 'ସର୍ତ୍ତାବଳୀ ଏବଂ ଗୋପନୀୟତା ନୀତି ସ୍ୱୀକାର କରନ୍ତୁ',
        agreeToAll: 'ମୁଁ ଉପରୋକ୍ତ ସମସ୍ତଙ୍କ ସହିତ ସହମତ',
      },
      landing: {
        welcome: 'ନ୍ୟାୟ ସାଥୀରେ ସ୍ୱାଗତ',
        tagline: 'ଆପଣଙ୍କ ଭାଷାରେ ତତ୍କ୍ଷଣାତ୍ ଆଇନଗତ ପ୍ରଥମ ସହାୟତା',
        selectLanguage: 'ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ',
        trustedCompanion: 'ଆପଣଙ୍କ ବିଶ୍ୱସ୍ତ ଆଇନଗତ ପ୍ରଥମ ସହାୟତା ସାଥୀ',
        back: 'ପଛକୁ',
        letsChat: 'କଥା ହେବା',
        talkToUs: 'ଆପଣଙ୍କ ଆଇନଗତ ପ୍ରଶ୍ନ ବିଷୟରେ ଆମ ସହ କଥା ହୁଅନ୍ତୁ',
      },
      about: {
        title: 'ନ୍ୟାୟ ସାଥୀ ବିଷୟରେ',
        back: 'ପଛକୁ',
        missionTitle: 'ଭାରତ ପାଇଁ ଆଇନଗତ ଜ୍ଞାନର ଲୋକତନ୍ତ୍ରୀକରଣ',
        missionDescription: 'ନ୍ୟାୟ ସାଥୀ କେବଳ ଏକ ଆପ୍ ନୁହେଁ—ଏହା ଏକ ମିଶନ। ପ୍ରତ୍ୟେକ ଭାରତୀୟଙ୍କୁ ସେମାନଙ୍କ ନିଜ ଭାଷାରେ ତତ୍କ୍ଷଣାତ୍, ସୁଲଭ ଏବଂ ସଠିକ୍ ଆଇନଗତ ମାର୍ଗଦର୍ଶନ ଦେବା ପାଇଁ ନିର୍ମିତ।',
        createdBy: 'ଭେଙ୍କଟ ରାମ ରେଡ୍ଡୀ ଗାନୁତୁଲା',
        creatorDescription: 'ସାମାଜିକ ପ୍ରଭାବ ପାଇଁ ଉତ୍ସାହ ଏବଂ "ଭାରତ ପାଇଁ ସମାଧାନ" ଦୃଷ୍ଟିକୋଣରେ ଅନୁପ୍ରାଣିତ, ଭେଙ୍କଟ ଆର୍ଥିକ ବ୍ୟବଧାନ ପୂରଣ କରିବା ଏବଂ ସାଧାରଣ ଭାରତୀୟମାନଙ୍କୁ ସଶକ୍ତ କରିବା ପାଇଁ ନ୍ୟାୟ ସାଥୀ ସୃଷ୍ଟି କଲେ।',
        profile: 'ପ୍ରୋଫାଇଲ୍',
        feature1Title: 'ସମାବେଶୀ ପ୍ରଯୁକ୍ତି',
        feature1Desc: '୧୨+ ଭାରତୀୟ ଭାଷାର ସମର୍ଥନ ସହ ଭାଷା ବାଧା ଭାଙ୍ଗି, ପ୍ରତ୍ୟେକ ନାଗରିକଙ୍କ ପାଇଁ ଆଇନଗତ ସୂଚନା ସୁଲଭ କରିବା।',
        feature2Title: 'ସଶକ୍ତୀକରଣ',
        feature2Desc: 'ଜଟିଳ ଆଇନଗତ ଶବ୍ଦାବଳୀକୁ ସରଳ, କାର୍ଯ୍ୟକ୍ଷମ ପରାମର୍ଶରେ ପରିଣତ କରିବା ଯାହା ସମସ୍ତେ ବୁଝିପାରିବେ।',
        feature3Title: 'ସହାନୁଭୂତି ସହ ସେବା',
        feature3Desc: 'ପ୍ରଥମେ ଶୁଣିବା, ଆପଣଙ୍କ ପରିସ୍ଥିତି ବୁଝିବା ଏବଂ ଯତ୍ନ ସହ ମାର୍ଗଦର୍ଶନ ଦେବା AI ସାଥୀ।',
        footer: 'ଭେଙ୍କଟ ରାମ ରେଡ୍ଡୀ ଗାନୁତୁଲା ❤️ ସହ ଭାରତ ପାଇଁ ନିର୍ମିତ',
      },
    },
  },
  UR: {
    code: 'UR',
    name: 'Urdu',
    nativeName: 'اردو',
    fontClass: 'font-urdu',
    direction: 'rtl',
    ttsVoice: 'ur-IN-Wavenet-A',
    disclaimer: 'یہ قانونی مشورہ نہیں ہے۔ صرف عام معلومات۔',
    ui: {
      startConsultation: 'قانونی مشاورت شروع کریں',
      tapToSpeak: 'بولنے کے لیے ٹیپ کریں',
      listening: 'سن رہا ہوں',
      analyzing: 'تجزیہ کر رہا ہوں',
      speaking: 'بول رہا ہوں',
      uploadDocument: 'دستاویز اپلوڈ کریں',
      typeMessage: 'اپنا پیغام ٹائپ کریں...',
      send: 'بھیجیں',
      emergency: 'ایمرجنسی',
      resources: 'وسائل',
      info: 'معلومات',
      admin: 'منتظم',
      startFresh: 'نئے سرے سے شروع کریں',
      helpline: 'ہیلپ لائن',
      attach: 'منسلک کریں',
      voice: 'آواز',
      text: 'ٹیکسٹ',
      connected: 'متصل',
      offline: 'آف لائن',
      youSaid: 'آپ نے کہا',
      welcomeMessage: 'السلام علیکم! میں نیائے ساتھی ہوں، آپ کا قانونی دوست۔ آج آپ کے ذہن میں کیا ہے؟ میں آپ کے قانونی حقوق سمجھنے میں مدد کرنے کے لیے یہاں ہوں۔',
      thinking: 'سوچ رہا ہوں...',
      processing: 'پروسیسنگ',
      transcribing: 'لکھ رہا ہوں',
      listen: 'سنیں',
      stop: 'روکیں',
      references: 'حوالہ جات',
      newSessionStarted: 'نیا سیشن شروع ہوا',
      newSessionDesc: 'آپ کی گفتگو صاف ہو گئی',
      onboarding: {
        talkToMe: 'مجھ سے بات کریں',
        talkToMeDesc: 'بس مائیک ٹیپ کریں اور اپنا سوال پوچھیں۔ دوست سے بات کرتے ہیں جیسے قدرتی طور پر بولیں!',
        switchToText: 'ٹیکسٹ پر جائیں',
        switchToTextDesc: 'ٹائپ کرنا پسند ہے؟ نیچے کی بار میں سوئچ استعمال کرکے ٹیکسٹ موڈ پر جائیں۔',
        uploadDocs: 'دستاویزات اپلوڈ کریں',
        uploadDocsDesc: 'AI تجزیے کے لیے قانونی دستاویزات اپلوڈ کریں۔ ہم PDF، DOCX، XLSX، CSV اور تصاویر کی حمایت کرتے ہیں۔',
        listenResponses: 'جوابات سنیں',
        listenResponsesDesc: 'اپنی زبان میں سننے کے لیے کسی بھی جواب پر اسپیکر آئیکن پر کلک کریں۔',
        skip: 'چھوڑیں',
        next: 'اگلا',
        getStarted: 'شروع کریں',
        stepOf: 'قدم {current} میں سے {total}',
      },
      consent: {
        byUsing: 'نیائے ساتھی استعمال کرتے ہوئے، آپ رضامند ہیں:',
        shareLocation: 'متعلقہ مقامی قانونی مشورے کے لیے اپنا مقام شیئر کریں',
        allowLogging: 'سیکیورٹی کے لیے گمنام کنکشن لاگنگ کی اجازت دیں',
        helpImprove: 'بہتری کے لیے چیٹس سے سیکھنے دیں (تمام ڈیٹا گمنام رہتا ہے)',
        acceptTerms: 'شرائط اور رازداری کی پالیسی قبول کریں',
        agreeToAll: 'میں مندرجہ بالا سب سے متفق ہوں',
      },
      landing: {
        welcome: 'نیائے ساتھی میں خوش آمدید',
        tagline: 'آپ کی زبان میں فوری قانونی ابتدائی طبی امداد',
        selectLanguage: 'اپنی زبان منتخب کریں',
        trustedCompanion: 'آپ کا قابل اعتماد قانونی ابتدائی طبی امداد ساتھی',
        back: 'واپس',
        letsChat: 'بات کریں',
        talkToUs: 'اپنے قانونی سوالات کے بارے میں ہم سے بات کریں',
      },
      about: {
        title: 'نیائے ساتھی کے بارے میں',
        back: 'واپس',
        missionTitle: 'بھارت کے لیے قانونی علم کی جمہوریت',
        missionDescription: 'نیائے ساتھی صرف ایک ایپ نہیں ہے—یہ ایک مشن ہے۔ ہر ہندوستانی کو ان کی اپنی زبان میں فوری، قابل رسائی اور درست قانونی رہنمائی فراہم کرنے کے لیے بنایا گیا۔',
        createdBy: 'وینکٹ رام ریڈی گانوتولا',
        creatorDescription: 'سماجی اثر کے لیے جوش اور "بھارت کے لیے حل" کے وژن سے متاثر، وینکٹ نے معاشی فرق کو پورا کرنے اور عام ہندوستانیوں کو بااختیار بنانے کے لیے نیائے ساتھی بنایا۔',
        profile: 'پروفائل',
        feature1Title: 'جامع ٹیکنالوجی',
        feature1Desc: '12+ ہندوستانی زبانوں کی حمایت کے ساتھ زبان کی رکاوٹیں توڑتے ہوئے، ہر شہری کے لیے قانونی معلومات قابل رسائی بنانا۔',
        feature2Title: 'بااختیار بنانا',
        feature2Desc: 'پیچیدہ قانونی اصطلاحات کو سادہ، قابل عمل مشورے میں تبدیل کرنا جو کوئی بھی سمجھ سکے۔',
        feature3Title: 'ہمدردی کے ساتھ خدمت',
        feature3Desc: 'پہلے سننے والا، آپ کی صورتحال سمجھنے والا، اور خیال رکھتے ہوئے رہنمائی کرنے والا AI ساتھی۔',
        footer: 'وینکٹ رام ریڈی گانوتولا نے ❤️ کے ساتھ بھارت کے لیے بنایا',
      },
    },
  },
};

export const DEFAULT_LANGUAGE: LanguageCode = 'EN';

export const getLanguageConfig = (code: LanguageCode): LanguageConfig => {
  return LANGUAGES[code] || LANGUAGES[DEFAULT_LANGUAGE];
};

export const getAllLanguages = (): LanguageConfig[] => {
  return Object.values(LANGUAGES);
};
