export type LanguageCode = 'HI' | 'EN' | 'BN' | 'TA' | 'TE' | 'MR' | 'GU' | 'KN' | 'ML' | 'PA' | 'OR' | 'UR';

export interface LanguageConfig {
  code: LanguageCode;
  name: string;
  nativeName: string;
  fontClass: string;
  direction: 'ltr' | 'rtl';
  ttsVoice: string;
  disclaimer: string;
  ui: {
    startConsultation: string;
    tapToSpeak: string;
    listening: string;
    analyzing: string;
    speaking: string;
    uploadDocument: string;
    typeMessage: string;
    send: string;
    emergency: string;
    resources: string;
    info: string;
    admin: string;
    startFresh: string;
    helpline: string;
    attach: string;
    voice: string;
    text: string;
    connected: string;
    offline: string;
    youSaid: string;
    welcomeMessage: string;
    thinking: string;
    processing: string;
    listen: string;
    stop: string;
    references: string;
  };
}

export const LANGUAGES: Record<LanguageCode, LanguageConfig> = {
  HI: {
    code: 'HI',
    name: 'Hindi',
    nativeName: 'हिंदी',
    fontClass: 'font-hindi',
    direction: 'ltr',
    ttsVoice: 'hi-IN-Neural2-A',
    disclaimer: 'यह कानूनी सलाह नहीं है। यह केवल सामान्य जानकारी है।',
    ui: {
      startConsultation: 'कानूनी परामर्श शुरू करें',
      tapToSpeak: 'बोलने के लिए टैप करें',
      listening: 'सुन रहा हूँ',
      analyzing: 'विश्लेषण कर रहा हूँ',
      speaking: 'बोल रहा हूँ',
      uploadDocument: 'दस्तावेज़ अपलोड करें',
      typeMessage: 'अपना संदेश लिखें...',
      send: 'भेजें',
      emergency: 'आपातकाल',
      resources: 'संसाधन',
      info: 'जानकारी',
      admin: 'व्यवस्थापक',
      startFresh: 'नया शुरू करें',
      helpline: 'हेल्पलाइन',
      attach: 'संलग्न करें',
      voice: 'आवाज़',
      text: 'टेक्स्ट',
      connected: 'कनेक्टेड',
      offline: 'ऑफ़लाइन',
      youSaid: 'आपने कहा',
      welcomeMessage: 'नमस्ते! मैं न्याय साथी हूँ, आपका कानूनी मित्र। आज आपके मन में क्या है? मैं आपके कानूनी अधिकारों को समझने और किसी भी कानूनी प्रश्न में मार्गदर्शन करने के लिए यहाँ हूँ।',
      thinking: 'सोच रहा हूँ...',
      processing: 'प्रोसेसिंग',
      listen: 'सुनें',
      stop: 'रोकें',
      references: 'संदर्भ',
    },
  },
  EN: {
    code: 'EN',
    name: 'English',
    nativeName: 'English',
    fontClass: 'font-sans',
    direction: 'ltr',
    ttsVoice: 'en-IN-Neural2-A',
    disclaimer: 'This is NOT legal advice. General information only.',
    ui: {
      startConsultation: 'Start Legal Consultation',
      tapToSpeak: 'Tap to speak',
      listening: 'Listening',
      analyzing: 'Analyzing',
      speaking: 'Speaking',
      uploadDocument: 'Upload Document',
      typeMessage: 'Type your message...',
      send: 'Send',
      emergency: 'Emergency',
      resources: 'Resources',
      info: 'Info',
      admin: 'Admin',
      startFresh: 'Start Fresh',
      helpline: 'Helpline',
      attach: 'Attach',
      voice: 'Voice',
      text: 'Text',
      connected: 'Connected',
      offline: 'Offline',
      youSaid: 'YOU SAID',
      welcomeMessage: "Hey there! I'm Nyay Saathi, your legal buddy. What's on your mind today? I'm here to help you understand your legal rights and guide you through any legal questions you might have.",
      thinking: 'Thinking...',
      processing: 'Processing',
      listen: 'Listen',
      stop: 'Stop',
      references: 'References',
    },
  },
  BN: {
    code: 'BN',
    name: 'Bengali',
    nativeName: 'বাংলা',
    fontClass: 'font-bengali',
    direction: 'ltr',
    ttsVoice: 'bn-IN-Neural2-A',
    disclaimer: 'এটি আইনি পরামর্শ নয়। শুধুমাত্র সাধারণ তথ্য।',
    ui: {
      startConsultation: 'আইনি পরামর্শ শুরু করুন',
      tapToSpeak: 'কথা বলতে ট্যাপ করুন',
      listening: 'শুনছি',
      analyzing: 'বিশ্লেষণ করছি',
      speaking: 'বলছি',
      uploadDocument: 'নথি আপলোড করুন',
      typeMessage: 'আপনার বার্তা লিখুন...',
      send: 'পাঠান',
      emergency: 'জরুরি',
      resources: 'সম্পদ',
      info: 'তথ্য',
      admin: 'অ্যাডমিন',
      startFresh: 'নতুন শুরু',
      helpline: 'হেল্পলাইন',
      attach: 'সংযুক্ত করুন',
      voice: 'ভয়েস',
      text: 'টেক্সট',
      connected: 'সংযুক্ত',
      offline: 'অফলাইন',
      youSaid: 'আপনি বলেছেন',
      welcomeMessage: 'হ্যালো! আমি ন্যায় সাথী, আপনার আইনি বন্ধু। আজ আপনার মনে কী আছে? আমি আপনার আইনি অধিকার বুঝতে এবং আপনার আইনি প্রশ্নে সাহায্য করতে এখানে আছি।',
      thinking: 'ভাবছি...',
      processing: 'প্রক্রিয়াকরণ',
      listen: 'শুনুন',
      stop: 'বন্ধ করুন',
      references: 'তথ্যসূত্র',
    },
  },
  TA: {
    code: 'TA',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    fontClass: 'font-tamil',
    direction: 'ltr',
    ttsVoice: 'ta-IN-Neural2-A',
    disclaimer: 'இது சட்ட ஆலோசனை அல்ல। பொது தகவல் மட்டுமே।',
    ui: {
      startConsultation: 'சட்ட ஆலோசனை தொடங்கு',
      tapToSpeak: 'பேச தட்டவும்',
      listening: 'கேட்கிறேன்',
      analyzing: 'பகுப்பாய்வு செய்கிறேன்',
      speaking: 'பேசுகிறேன்',
      uploadDocument: 'ஆவணத்தை பதிவேற்றவும்',
      typeMessage: 'உங்கள் செய்தியை எழுதுங்கள்...',
      send: 'அனுப்பு',
      emergency: 'அவசரம்',
      resources: 'வளங்கள்',
      info: 'தகவல்',
      admin: 'நிர்வாகி',
      startFresh: 'புதிதாக தொடங்கு',
      helpline: 'உதவி எண்',
      attach: 'இணைக்கவும்',
      voice: 'குரல்',
      text: 'உரை',
      connected: 'இணைக்கப்பட்டது',
      offline: 'ஆஃப்லைன்',
      youSaid: 'நீங்கள் சொன்னது',
      welcomeMessage: 'வணக்கம்! நான் நியாய சாதி, உங்கள் சட்ட நண்பன். இன்று உங்கள் மனதில் என்ன இருக்கிறது? உங்கள் சட்ட உரிமைகளை புரிந்துகொள்ள உதவ நான் இங்கே இருக்கிறேன்.',
      thinking: 'யோசிக்கிறேன்...',
      processing: 'செயலாக்கம்',
      listen: 'கேளுங்கள்',
      stop: 'நிறுத்து',
      references: 'குறிப்புகள்',
    },
  },
  TE: {
    code: 'TE',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    fontClass: 'font-telugu',
    direction: 'ltr',
    ttsVoice: 'te-IN-Neural2-A',
    disclaimer: 'ఇది చట్టపరమైన సలహా కాదు. సాధారణ సమాచారం మాత్రమే.',
    ui: {
      startConsultation: 'చట్టపరమైన సలహా ప్రారంభించండి',
      tapToSpeak: 'మాట్లాడటానికి నొక్కండి',
      listening: 'వింటున్నాను',
      analyzing: 'విశ్లేషిస్తున్నాను',
      speaking: 'మాట్లాడుతున్నాను',
      uploadDocument: 'పత్రం అప్‌లోడ్ చేయండి',
      typeMessage: 'మీ సందేశం టైప్ చేయండి...',
      send: 'పంపండి',
      emergency: 'అత్యవసర',
      resources: 'వనరులు',
      info: 'సమాచారం',
      admin: 'నిర్వాహకుడు',
      startFresh: 'కొత్తగా ప్రారంభించు',
      helpline: 'హెల్ప్‌లైన్',
      attach: 'జోడించు',
      voice: 'వాయిస్',
      text: 'టెక్స్ట్',
      connected: 'కనెక్ట్ అయింది',
      offline: 'ఆఫ్‌లైన్',
      youSaid: 'మీరు చెప్పారు',
      welcomeMessage: 'హలో! నేను న్యాయ సాథి, మీ చట్టపరమైన మిత్రుడు. ఈరోజు మీ మనసులో ఏముంది? మీ చట్టపరమైన హక్కులను అర్థం చేసుకోవడంలో సహాయం చేయడానికి నేను ఇక్కడ ఉన్నాను.',
      thinking: 'ఆలోచిస్తున్నాను...',
      processing: 'ప్రాసెసింగ్',
      listen: 'వినండి',
      stop: 'ఆపు',
      references: 'సూచనలు',
    },
  },
  MR: {
    code: 'MR',
    name: 'Marathi',
    nativeName: 'मराठी',
    fontClass: 'font-hindi',
    direction: 'ltr',
    ttsVoice: 'mr-IN-Neural2-A',
    disclaimer: 'हा कायदेशीर सल्ला नाही. केवळ सामान्य माहिती.',
    ui: {
      startConsultation: 'कायदेशीर सल्ला सुरू करा',
      tapToSpeak: 'बोलण्यासाठी टॅप करा',
      listening: 'ऐकत आहे',
      analyzing: 'विश्लेषण करत आहे',
      speaking: 'बोलत आहे',
      uploadDocument: 'दस्तऐवज अपलोड करा',
      typeMessage: 'तुमचा संदेश टाइप करा...',
      send: 'पाठवा',
      emergency: 'आणीबाणी',
      resources: 'संसाधने',
      info: 'माहिती',
      admin: 'प्रशासक',
      startFresh: 'नव्याने सुरू करा',
      helpline: 'हेल्पलाइन',
      attach: 'जोडा',
      voice: 'आवाज',
      text: 'मजकूर',
      connected: 'कनेक्ट',
      offline: 'ऑफलाइन',
      youSaid: 'तुम्ही म्हणालात',
      welcomeMessage: 'नमस्कार! मी न्याय साथी, तुमचा कायदेशीर मित्र. आज तुमच्या मनात काय आहे? तुमचे कायदेशीर हक्क समजून घेण्यास मदत करण्यासाठी मी इथे आहे.',
      thinking: 'विचार करत आहे...',
      processing: 'प्रक्रिया',
      listen: 'ऐका',
      stop: 'थांबा',
      references: 'संदर्भ',
    },
  },
  GU: {
    code: 'GU',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    fontClass: 'font-gujarati',
    direction: 'ltr',
    ttsVoice: 'gu-IN-Neural2-A',
    disclaimer: 'આ કાનૂની સલાહ નથી. ફક્ત સામાન્ય માહિતી.',
    ui: {
      startConsultation: 'કાનૂની સલાહ શરૂ કરો',
      tapToSpeak: 'બોલવા માટે ટૅપ કરો',
      listening: 'સાંભળી રહ્યો છું',
      analyzing: 'વિશ્લેષણ કરી રહ્યો છું',
      speaking: 'બોલી રહ્યો છું',
      uploadDocument: 'દસ્તાવેજ અપલોડ કરો',
      typeMessage: 'તમારો સંદેશ લખો...',
      send: 'મોકલો',
      emergency: 'કટોકટી',
      resources: 'સંસાધનો',
      info: 'માહિતી',
      admin: 'સંચાલક',
      startFresh: 'નવેસરથી શરૂ કરો',
      helpline: 'હેલ્પલાઇન',
      attach: 'જોડો',
      voice: 'અવાજ',
      text: 'ટેક્સ્ટ',
      connected: 'કનેક્ટેડ',
      offline: 'ઑફલાઇન',
      youSaid: 'તમે કહ્યું',
      welcomeMessage: 'નમસ્તે! હું ન્યાય સાથી, તમારો કાનૂની મિત્ર. આજે તમારા મનમાં શું છે? તમારા કાનૂની અધિકારો સમજવામાં મદદ કરવા હું અહીં છું.',
      thinking: 'વિચારી રહ્યો છું...',
      processing: 'પ્રોસેસિંગ',
      listen: 'સાંભળો',
      stop: 'બંધ કરો',
      references: 'સંદર્ભો',
    },
  },
  KN: {
    code: 'KN',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    fontClass: 'font-kannada',
    direction: 'ltr',
    ttsVoice: 'kn-IN-Neural2-A',
    disclaimer: 'ಇದು ಕಾನೂನು ಸಲಹೆ ಅಲ್ಲ. ಸಾಮಾನ್ಯ ಮಾಹಿತಿ ಮಾತ್ರ.',
    ui: {
      startConsultation: 'ಕಾನೂನು ಸಮಾಲೋಚನೆ ಪ್ರಾರಂಭಿಸಿ',
      tapToSpeak: 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
      listening: 'ಕೇಳುತ್ತಿದ್ದೇನೆ',
      analyzing: 'ವಿಶ್ಲೇಷಿಸುತ್ತಿದ್ದೇನೆ',
      speaking: 'ಮಾತನಾಡುತ್ತಿದ್ದೇನೆ',
      uploadDocument: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      typeMessage: 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
      send: 'ಕಳುಹಿಸಿ',
      emergency: 'ತುರ್ತು',
      resources: 'ಸಂಪನ್ಮೂಲಗಳು',
      info: 'ಮಾಹಿತಿ',
      admin: 'ನಿರ್ವಾಹಕ',
      startFresh: 'ಹೊಸದಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
      helpline: 'ಹೆಲ್ಪ್‌ಲೈನ್',
      attach: 'ಲಗತ್ತಿಸಿ',
      voice: 'ಧ್ವನಿ',
      text: 'ಪಠ್ಯ',
      connected: 'ಸಂಪರ್ಕಿತ',
      offline: 'ಆಫ್‌ಲೈನ್',
      youSaid: 'ನೀವು ಹೇಳಿದ್ದು',
      welcomeMessage: 'ನಮಸ್ಕಾರ! ನಾನು ನ್ಯಾಯ ಸಾಥಿ, ನಿಮ್ಮ ಕಾನೂನು ಸ್ನೇಹಿತ. ಇಂದು ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿ ಏನಿದೆ? ನಿಮ್ಮ ಕಾನೂನು ಹಕ್ಕುಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡಲು ನಾನು ಇಲ್ಲಿದ್ದೇನೆ.',
      thinking: 'ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ...',
      processing: 'ಪ್ರಕ್ರಿಯೆ',
      listen: 'ಕೇಳಿ',
      stop: 'ನಿಲ್ಲಿಸಿ',
      references: 'ಉಲ್ಲೇಖಗಳು',
    },
  },
  ML: {
    code: 'ML',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    fontClass: 'font-malayalam',
    direction: 'ltr',
    ttsVoice: 'ml-IN-Neural2-A',
    disclaimer: 'ഇത് നിയമ ഉപദേശമല്ല. പൊതു വിവരങ്ങൾ മാത്രം.',
    ui: {
      startConsultation: 'നിയമ കൺസൾട്ടേഷൻ ആരംഭിക്കുക',
      tapToSpeak: 'സംസാരിക്കാൻ ടാപ്പ് ചെയ്യുക',
      listening: 'കേൾക്കുന്നു',
      analyzing: 'വിശകലനം ചെയ്യുന്നു',
      speaking: 'സംസാരിക്കുന്നു',
      uploadDocument: 'രേഖ അപ്‌ലോഡ് ചെയ്യുക',
      typeMessage: 'നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
      send: 'അയയ്ക്കുക',
      emergency: 'അടിയന്തരം',
      resources: 'വിഭവങ്ങൾ',
      info: 'വിവരങ്ങൾ',
      admin: 'അഡ്മിൻ',
      startFresh: 'പുതുതായി തുടങ്ങുക',
      helpline: 'ഹെൽപ്പ്‌ലൈൻ',
      attach: 'അറ്റാച്ച് ചെയ്യുക',
      voice: 'ശബ്ദം',
      text: 'ടെക്സ്റ്റ്',
      connected: 'കണക്റ്റഡ്',
      offline: 'ഓഫ്‌ലൈൻ',
      youSaid: 'നിങ്ങൾ പറഞ്ഞത്',
      welcomeMessage: 'ഹലോ! ഞാൻ ന്യായ സാഥി, നിങ്ങളുടെ നിയമ സുഹൃത്ത്. ഇന്ന് നിങ്ങളുടെ മനസ്സിൽ എന്താണ്? നിങ്ങളുടെ നിയമ അവകാശങ്ങൾ മനസ്സിലാക്കാൻ സഹായിക്കാൻ ഞാൻ ഇവിടെയുണ്ട്.',
      thinking: 'ചിന്തിക്കുന്നു...',
      processing: 'പ്രോസസ്സിംഗ്',
      listen: 'കേൾക്കുക',
      stop: 'നിർത്തുക',
      references: 'റഫറൻസുകൾ',
    },
  },
  PA: {
    code: 'PA',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    fontClass: 'font-punjabi',
    direction: 'ltr',
    ttsVoice: 'pa-IN-Neural2-A',
    disclaimer: 'ਇਹ ਕਾਨੂੰਨੀ ਸਲਾਹ ਨਹੀਂ ਹੈ। ਸਿਰਫ਼ ਆਮ ਜਾਣਕਾਰੀ।',
    ui: {
      startConsultation: 'ਕਾਨੂੰਨੀ ਸਲਾਹ ਸ਼ੁਰੂ ਕਰੋ',
      tapToSpeak: 'ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ',
      listening: 'ਸੁਣ ਰਿਹਾ ਹਾਂ',
      analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹਾਂ',
      speaking: 'ਬੋਲ ਰਿਹਾ ਹਾਂ',
      uploadDocument: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
      typeMessage: 'ਆਪਣਾ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...',
      send: 'ਭੇਜੋ',
      emergency: 'ਐਮਰਜੈਂਸੀ',
      resources: 'ਸਰੋਤ',
      info: 'ਜਾਣਕਾਰੀ',
      admin: 'ਪ੍ਰਬੰਧਕ',
      startFresh: 'ਨਵੇਂ ਸਿਰੇ ਤੋਂ ਸ਼ੁਰੂ ਕਰੋ',
      helpline: 'ਹੈਲਪਲਾਈਨ',
      attach: 'ਜੋੜੋ',
      voice: 'ਆਵਾਜ਼',
      text: 'ਟੈਕਸਟ',
      connected: 'ਕਨੈਕਟ',
      offline: 'ਆਫ਼ਲਾਈਨ',
      youSaid: 'ਤੁਸੀਂ ਕਿਹਾ',
      welcomeMessage: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਨਿਆਂ ਸਾਥੀ ਹਾਂ, ਤੁਹਾਡਾ ਕਾਨੂੰਨੀ ਦੋਸਤ। ਅੱਜ ਤੁਹਾਡੇ ਮਨ ਵਿੱਚ ਕੀ ਹੈ? ਮੈਂ ਤੁਹਾਡੇ ਕਾਨੂੰਨੀ ਹੱਕਾਂ ਨੂੰ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰਨ ਲਈ ਇੱਥੇ ਹਾਂ।',
      thinking: 'ਸੋਚ ਰਿਹਾ ਹਾਂ...',
      processing: 'ਪ੍ਰੋਸੈਸਿੰਗ',
      listen: 'ਸੁਣੋ',
      stop: 'ਰੋਕੋ',
      references: 'ਹਵਾਲੇ',
    },
  },
  OR: {
    code: 'OR',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    fontClass: 'font-odia',
    direction: 'ltr',
    ttsVoice: 'or-IN-Standard-A',
    disclaimer: 'ଏହା ଆଇନଗତ ପରାମର୍ଶ ନୁହେଁ। କେବଳ ସାଧାରଣ ସୂଚନା।',
    ui: {
      startConsultation: 'ଆଇନଗତ ପରାମର୍ଶ ଆରମ୍ଭ କରନ୍ତୁ',
      tapToSpeak: 'କହିବାକୁ ଟ୍ୟାପ୍ କରନ୍ତୁ',
      listening: 'ଶୁଣୁଛି',
      analyzing: 'ବିଶ୍ଲେଷଣ କରୁଛି',
      speaking: 'କହୁଛି',
      uploadDocument: 'ଡକ୍ୟୁମେଣ୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
      typeMessage: 'ଆପଣଙ୍କ ସନ୍ଦେଶ ଟାଇପ୍ କରନ୍ତୁ...',
      send: 'ପଠାନ୍ତୁ',
      emergency: 'ଜରୁରୀ',
      resources: 'ସମ୍ବଳ',
      info: 'ସୂଚନା',
      admin: 'ପ୍ରଶାସକ',
      startFresh: 'ନୂଆରୁ ଆରମ୍ଭ କରନ୍ତୁ',
      helpline: 'ହେଲ୍ପଲାଇନ୍',
      attach: 'ସଂଲଗ୍ନ କରନ୍ତୁ',
      voice: 'ସ୍ୱର',
      text: 'ଟେକ୍ସଟ୍',
      connected: 'ସଂଯୁକ୍ତ',
      offline: 'ଅଫଲାଇନ୍',
      youSaid: 'ଆପଣ କହିଲେ',
      welcomeMessage: 'ନମସ୍କାର! ମୁଁ ନ୍ୟାୟ ସାଥୀ, ଆପଣଙ୍କ ଆଇନଗତ ସାଙ୍ଗ। ଆଜି ଆପଣଙ୍କ ମନରେ କଣ ଅଛି? ଆପଣଙ୍କ ଆଇନଗତ ଅଧିକାର ବୁଝିବାରେ ସାହାଯ୍ୟ କରିବାକୁ ମୁଁ ଏଠାରେ ଅଛି।',
      thinking: 'ଭାବୁଛି...',
      processing: 'ପ୍ରକ୍ରିୟାକରଣ',
      listen: 'ଶୁଣନ୍ତୁ',
      stop: 'ବନ୍ଦ କରନ୍ତୁ',
      references: 'ସନ୍ଦର୍ଭ',
    },
  },
  UR: {
    code: 'UR',
    name: 'Urdu',
    nativeName: 'اردو',
    fontClass: 'font-urdu',
    direction: 'rtl',
    ttsVoice: 'ur-IN-Standard-A',
    disclaimer: 'یہ قانونی مشورہ نہیں ہے۔ صرف عام معلومات۔',
    ui: {
      startConsultation: 'قانونی مشاورت شروع کریں',
      tapToSpeak: 'بولنے کے لیے ٹیپ کریں',
      listening: 'سن رہا ہوں',
      analyzing: 'تجزیہ کر رہا ہوں',
      speaking: 'بول رہا ہوں',
      uploadDocument: 'دستاویز اپلوڈ کریں',
      typeMessage: 'اپنا پیغام ٹائپ کریں...',
      send: 'بھیجیں',
      emergency: 'ایمرجنسی',
      resources: 'وسائل',
      info: 'معلومات',
      admin: 'منتظم',
      startFresh: 'نئے سرے سے شروع کریں',
      helpline: 'ہیلپ لائن',
      attach: 'منسلک کریں',
      voice: 'آواز',
      text: 'ٹیکسٹ',
      connected: 'متصل',
      offline: 'آف لائن',
      youSaid: 'آپ نے کہا',
      welcomeMessage: 'السلام علیکم! میں نیائے ساتھی ہوں، آپ کا قانونی دوست۔ آج آپ کے ذہن میں کیا ہے؟ میں آپ کے قانونی حقوق سمجھنے میں مدد کرنے کے لیے یہاں ہوں۔',
      thinking: 'سوچ رہا ہوں...',
      processing: 'پروسیسنگ',
      listen: 'سنیں',
      stop: 'روکیں',
      references: 'حوالہ جات',
    },
  },
};

export const DEFAULT_LANGUAGE: LanguageCode = 'EN';

export const getLanguageConfig = (code: LanguageCode): LanguageConfig => {
  return LANGUAGES[code] || LANGUAGES[DEFAULT_LANGUAGE];
};

export const getAllLanguages = (): LanguageConfig[] => {
  return Object.values(LANGUAGES);
};
