export type LanguageCode = 'HI' | 'EN' | 'BN' | 'TA' | 'TE' | 'MR' | 'GU' | 'KN' | 'ML' | 'PA' | 'OR' | 'UR';

export interface OnboardingTranslations {
  talkToMe: string;
  talkToMeDesc: string;
  switchToText: string;
  switchToTextDesc: string;
  uploadDocs: string;
  uploadDocsDesc: string;
  listenResponses: string;
  listenResponsesDesc: string;
  skip: string;
  next: string;
  getStarted: string;
  stepOf: string;
}

export interface LanguageConfig {
  code: LanguageCode;
  name: string;
  nativeName: string;
  fontClass: string;
  direction: 'ltr' | 'rtl';
  ttsVoice: string;
  disclaimer: string;
  ui: {
    startConsultation: string;
    tapToSpeak: string;
    listening: string;
    analyzing: string;
    speaking: string;
    uploadDocument: string;
    typeMessage: string;
    send: string;
    emergency: string;
    resources: string;
    info: string;
    admin: string;
    startFresh: string;
    helpline: string;
    attach: string;
    voice: string;
    text: string;
    connected: string;
    offline: string;
    youSaid: string;
    welcomeMessage: string;
    thinking: string;
    processing: string;
    transcribing: string;
    listen: string;
    stop: string;
    references: string;
    onboarding: OnboardingTranslations;
  };
}

export const LANGUAGES: Record<LanguageCode, LanguageConfig> = {
  HI: {
    code: 'HI',
    name: 'Hindi',
    nativeName: 'हिंदी',
    fontClass: 'font-hindi',
    direction: 'ltr',
    ttsVoice: 'hi-IN-Neural2-A',
    disclaimer: 'यह कानूनी सलाह नहीं है। यह केवल सामान्य जानकारी है।',
    ui: {
      startConsultation: 'कानूनी परामर्श शुरू करें',
      tapToSpeak: 'बोलने के लिए टैप करें',
      listening: 'सुन रहा हूँ',
      analyzing: 'विश्लेषण कर रहा हूँ',
      speaking: 'बोल रहा हूँ',
      uploadDocument: 'दस्तावेज़ अपलोड करें',
      typeMessage: 'अपना संदेश लिखें...',
      send: 'भेजें',
      emergency: 'आपातकाल',
      resources: 'संसाधन',
      info: 'जानकारी',
      admin: 'व्यवस्थापक',
      startFresh: 'नया शुरू करें',
      helpline: 'हेल्पलाइन',
      attach: 'संलग्न करें',
      voice: 'आवाज़',
      text: 'टेक्स्ट',
      connected: 'कनेक्टेड',
      offline: 'ऑफ़लाइन',
      youSaid: 'आपने कहा',
      welcomeMessage: 'नमस्ते! मैं न्याय साथी हूँ, आपका कानूनी मित्र। आज आपके मन में क्या है? मैं आपके कानूनी अधिकारों को समझने और किसी भी कानूनी प्रश्न में मार्गदर्शन करने के लिए यहाँ हूँ।',
      thinking: 'सोच रहा हूँ...',
      processing: 'प्रोसेसिंग',
      transcribing: 'लिख रहा हूँ',
      listen: 'सुनें',
      stop: 'रोकें',
      references: 'संदर्भ',
      onboarding: {
        talkToMe: 'मुझसे बात करो',
        talkToMeDesc: 'बस माइक को टैप करें और अपना सवाल पूछें। एक दोस्त की तरह स्वाभाविक रूप से बोलें!',
        switchToText: 'टेक्स्ट पर स्विच करें',
        switchToTextDesc: 'टाइप करना पसंद है? नीचे की बार में स्विच का उपयोग करके टेक्स्ट मोड पर जाएं।',
        uploadDocs: 'दस्तावेज़ अपलोड करें',
        uploadDocsDesc: 'AI विश्लेषण के लिए कानूनी दस्तावेज़ अपलोड करें। हम PDF, DOCX, XLSX, CSV और छवियों का समर्थन करते हैं।',
        listenResponses: 'जवाब सुनें',
        listenResponsesDesc: 'किसी भी जवाब पर स्पीकर आइकन पर क्लिक करें अपनी भाषा में सुनने के लिए।',
        skip: 'छोड़ें',
        next: 'अगला',
        getStarted: 'शुरू करें',
        stepOf: 'चरण {current} का {total}',
      },
    },
  },
  EN: {
    code: 'EN',
    name: 'English',
    nativeName: 'English',
    fontClass: 'font-sans',
    direction: 'ltr',
    ttsVoice: 'en-IN-Neural2-A',
    disclaimer: 'This is NOT legal advice. General information only.',
    ui: {
      startConsultation: 'Start Legal Consultation',
      tapToSpeak: 'Tap to speak',
      listening: 'Listening',
      analyzing: 'Analyzing',
      speaking: 'Speaking',
      uploadDocument: 'Upload Document',
      typeMessage: 'Type your message...',
      send: 'Send',
      emergency: 'Emergency',
      resources: 'Resources',
      info: 'Info',
      admin: 'Admin',
      startFresh: 'Start Fresh',
      helpline: 'Helpline',
      attach: 'Attach',
      voice: 'Voice',
      text: 'Text',
      connected: 'Connected',
      offline: 'Offline',
      youSaid: 'YOU SAID',
      welcomeMessage: "Hey there! I'm Nyay Saathi, your legal buddy. What's on your mind today? I'm here to help you understand your legal rights and guide you through any legal questions you might have.",
      thinking: 'Thinking...',
      processing: 'Processing',
      transcribing: 'Transcribing',
      listen: 'Listen',
      stop: 'Stop',
      references: 'References',
      onboarding: {
        talkToMe: 'Talk to Me',
        talkToMeDesc: 'Just tap the mic and ask your question. Speak naturally like you would to a friend!',
        switchToText: 'Switch to Text',
        switchToTextDesc: 'Prefer typing? Toggle to text mode using the switch in the bottom bar.',
        uploadDocs: 'Upload Documents',
        uploadDocsDesc: 'Upload legal documents for AI analysis. We support PDF, DOCX, XLSX, CSV, and images.',
        listenResponses: 'Listen to Responses',
        listenResponsesDesc: 'Click the speaker icon on any response to hear it in your language.',
        skip: 'Skip',
        next: 'Next',
        getStarted: 'Get Started',
        stepOf: 'Step {current} of {total}',
      },
    },
  },
  BN: {
    code: 'BN',
    name: 'Bengali',
    nativeName: 'বাংলা',
    fontClass: 'font-bengali',
    direction: 'ltr',
    ttsVoice: 'bn-IN-Neural2-A',
    disclaimer: 'এটি আইনি পরামর্শ নয়। শুধুমাত্র সাধারণ তথ্য।',
    ui: {
      startConsultation: 'আইনি পরামর্শ শুরু করুন',
      tapToSpeak: 'কথা বলতে ট্যাপ করুন',
      listening: 'শুনছি',
      analyzing: 'বিশ্লেষণ করছি',
      speaking: 'বলছি',
      uploadDocument: 'নথি আপলোড করুন',
      typeMessage: 'আপনার বার্তা লিখুন...',
      send: 'পাঠান',
      emergency: 'জরুরি',
      resources: 'সম্পদ',
      info: 'তথ্য',
      admin: 'অ্যাডমিন',
      startFresh: 'নতুন শুরু',
      helpline: 'হেল্পলাইন',
      attach: 'সংযুক্ত করুন',
      voice: 'ভয়েস',
      text: 'টেক্সট',
      connected: 'সংযুক্ত',
      offline: 'অফলাইন',
      youSaid: 'আপনি বলেছেন',
      welcomeMessage: 'হ্যালো! আমি ন্যায় সাথী, আপনার আইনি বন্ধু। আজ আপনার মনে কী আছে? আমি আপনার আইনি অধিকার বুঝতে এবং আপনার আইনি প্রশ্নে সাহায্য করতে এখানে আছি।',
      thinking: 'ভাবছি...',
      processing: 'প্রক্রিয়াকরণ',
      transcribing: 'লিখছি',
      listen: 'শুনুন',
      stop: 'বন্ধ করুন',
      references: 'তথ্যসূত্র',
      onboarding: {
        talkToMe: 'আমার সাথে কথা বলুন',
        talkToMeDesc: 'শুধু মাইক ট্যাপ করুন এবং আপনার প্রশ্ন জিজ্ঞাসা করুন। বন্ধুর মতো স্বাভাবিকভাবে কথা বলুন!',
        switchToText: 'টেক্সটে স্যুইচ করুন',
        switchToTextDesc: 'টাইপ করতে পছন্দ করেন? নিচের বারে সুইচ ব্যবহার করে টেক্সট মোডে যান।',
        uploadDocs: 'নথি আপলোড করুন',
        uploadDocsDesc: 'AI বিশ্লেষণের জন্য আইনি নথি আপলোড করুন। আমরা PDF, DOCX, XLSX, CSV এবং ছবি সমর্থন করি।',
        listenResponses: 'উত্তর শুনুন',
        listenResponsesDesc: 'আপনার ভাষায় শুনতে যেকোনো উত্তরে স্পিকার আইকনে ক্লিক করুন।',
        skip: 'এড়িয়ে যান',
        next: 'পরবর্তী',
        getStarted: 'শুরু করুন',
        stepOf: 'ধাপ {current} এর {total}',
      },
    },
  },
  TA: {
    code: 'TA',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    fontClass: 'font-tamil',
    direction: 'ltr',
    ttsVoice: 'ta-IN-Neural2-A',
    disclaimer: 'இது சட்ட ஆலோசனை அல்ல। பொது தகவல் மட்டுமே।',
    ui: {
      startConsultation: 'சட்ட ஆலோசனை தொடங்கு',
      tapToSpeak: 'பேச தட்டவும்',
      listening: 'கேட்கிறேன்',
      analyzing: 'பகுப்பாய்வு செய்கிறேன்',
      speaking: 'பேசுகிறேன்',
      uploadDocument: 'ஆவணத்தை பதிவேற்றவும்',
      typeMessage: 'உங்கள் செய்தியை எழுதுங்கள்...',
      send: 'அனுப்பு',
      emergency: 'அவசரம்',
      resources: 'வளங்கள்',
      info: 'தகவல்',
      admin: 'நிர்வாகி',
      startFresh: 'புதிதாக தொடங்கு',
      helpline: 'உதவி எண்',
      attach: 'இணைக்கவும்',
      voice: 'குரல்',
      text: 'உரை',
      connected: 'இணைக்கப்பட்டது',
      offline: 'ஆஃப்லைன்',
      youSaid: 'நீங்கள் சொன்னது',
      welcomeMessage: 'வணக்கம்! நான் நியாய சாதி, உங்கள் சட்ட நண்பன். இன்று உங்கள் மனதில் என்ன இருக்கிறது? உங்கள் சட்ட உரிமைகளை புரிந்துகொள்ள உதவ நான் இங்கே இருக்கிறேன்.',
      thinking: 'யோசிக்கிறேன்...',
      processing: 'செயலாக்கம்',
      transcribing: 'எழுதுகிறேன்',
      listen: 'கேளுங்கள்',
      stop: 'நிறுத்து',
      references: 'குறிப்புகள்',
      onboarding: {
        talkToMe: 'என்னிடம் பேசுங்கள்',
        talkToMeDesc: 'மைக்கை தட்டி உங்கள் கேள்வியை கேளுங்கள். நண்பரிடம் பேசுவது போல் இயல்பாக பேசுங்கள்!',
        switchToText: 'உரைக்கு மாறவும்',
        switchToTextDesc: 'டைப் செய்ய விரும்புகிறீர்களா? கீழே உள்ள பட்டியில் சுவிட்சைப் பயன்படுத்தி உரை பயன்முறைக்கு மாறவும்.',
        uploadDocs: 'ஆவணங்களை பதிவேற்றவும்',
        uploadDocsDesc: 'AI பகுப்பாய்வுக்கு சட்ட ஆவணங்களை பதிவேற்றவும். PDF, DOCX, XLSX, CSV மற்றும் படங்களை ஆதரிக்கிறோம்.',
        listenResponses: 'பதில்களை கேளுங்கள்',
        listenResponsesDesc: 'உங்கள் மொழியில் கேட்க எந்த பதிலிலும் ஸ்பீக்கர் ஐகானை கிளிக் செய்யவும்.',
        skip: 'தவிர்',
        next: 'அடுத்து',
        getStarted: 'தொடங்கு',
        stepOf: 'படி {current} இல் {total}',
      },
    },
  },
  TE: {
    code: 'TE',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    fontClass: 'font-telugu',
    direction: 'ltr',
    ttsVoice: 'te-IN-Neural2-A',
    disclaimer: 'ఇది చట్టపరమైన సలహా కాదు. సాధారణ సమాచారం మాత్రమే.',
    ui: {
      startConsultation: 'చట్టపరమైన సలహా ప్రారంభించండి',
      tapToSpeak: 'మాట్లాడటానికి నొక్కండి',
      listening: 'వింటున్నాను',
      analyzing: 'విశ్లేషిస్తున్నాను',
      speaking: 'మాట్లాడుతున్నాను',
      uploadDocument: 'పత్రం అప్‌లోడ్ చేయండి',
      typeMessage: 'మీ సందేశం టైప్ చేయండి...',
      send: 'పంపండి',
      emergency: 'అత్యవసర',
      resources: 'వనరులు',
      info: 'సమాచారం',
      admin: 'నిర్వాహకుడు',
      startFresh: 'కొత్తగా ప్రారంభించు',
      helpline: 'హెల్ప్‌లైన్',
      attach: 'జోడించు',
      voice: 'వాయిస్',
      text: 'టెక్స్ట్',
      connected: 'కనెక్ట్ అయింది',
      offline: 'ఆఫ్‌లైన్',
      youSaid: 'మీరు చెప్పారు',
      welcomeMessage: 'హలో! నేను న్యాయ సాథి, మీ చట్టపరమైన మిత్రుడు. ఈరోజు మీ మనసులో ఏముంది? మీ చట్టపరమైన హక్కులను అర్థం చేసుకోవడంలో సహాయం చేయడానికి నేను ఇక్కడ ఉన్నాను.',
      thinking: 'ఆలోచిస్తున్నాను...',
      processing: 'ప్రాసెసింగ్',
      transcribing: 'రాస్తున్నాను',
      listen: 'వినండి',
      stop: 'ఆపు',
      references: 'సూచనలు',
      onboarding: {
        talkToMe: 'నాతో మాట్లాడండి',
        talkToMeDesc: 'మైక్ ను ట్యాప్ చేసి మీ ప్రశ్న అడగండి. స్నేహితుడితో మాట్లాడినట్లు సహజంగా మాట్లాడండి!',
        switchToText: 'టెక్స్ట్ కు మారండి',
        switchToTextDesc: 'టైప్ చేయడం ఇష్టపడతారా? దిగువ బార్‌లో స్విచ్ ఉపయోగించి టెక్స్ట్ మోడ్‌కు మారండి.',
        uploadDocs: 'డాక్యుమెంట్లు అప్‌లోడ్ చేయండి',
        uploadDocsDesc: 'AI విశ్లేషణ కోసం చట్టపరమైన డాక్యుమెంట్లను అప్‌లోడ్ చేయండి. మేము PDF, DOCX, XLSX, CSV మరియు చిత్రాలకు మద్దతు ఇస్తాము.',
        listenResponses: 'స్పందనలు వినండి',
        listenResponsesDesc: 'మీ భాషలో వినడానికి ఏదైనా స్పందనపై స్పీకర్ ఐకాన్ క్లిక్ చేయండి.',
        skip: 'దాటవేయి',
        next: 'తదుపరి',
        getStarted: 'ప్రారంభించండి',
        stepOf: 'దశ {current} లో {total}',
      },
    },
  },
  MR: {
    code: 'MR',
    name: 'Marathi',
    nativeName: 'मराठी',
    fontClass: 'font-hindi',
    direction: 'ltr',
    ttsVoice: 'mr-IN-Neural2-A',
    disclaimer: 'हा कायदेशीर सल्ला नाही. केवळ सामान्य माहिती.',
    ui: {
      startConsultation: 'कायदेशीर सल्ला सुरू करा',
      tapToSpeak: 'बोलण्यासाठी टॅप करा',
      listening: 'ऐकत आहे',
      analyzing: 'विश्लेषण करत आहे',
      speaking: 'बोलत आहे',
      uploadDocument: 'दस्तऐवज अपलोड करा',
      typeMessage: 'तुमचा संदेश टाइप करा...',
      send: 'पाठवा',
      emergency: 'आणीबाणी',
      resources: 'संसाधने',
      info: 'माहिती',
      admin: 'प्रशासक',
      startFresh: 'नव्याने सुरू करा',
      helpline: 'हेल्पलाइन',
      attach: 'जोडा',
      voice: 'आवाज',
      text: 'मजकूर',
      connected: 'कनेक्ट',
      offline: 'ऑफलाइन',
      youSaid: 'तुम्ही म्हणालात',
      welcomeMessage: 'नमस्कार! मी न्याय साथी, तुमचा कायदेशीर मित्र. आज तुमच्या मनात काय आहे? तुमचे कायदेशीर हक्क समजून घेण्यास मदत करण्यासाठी मी इथे आहे.',
      thinking: 'विचार करत आहे...',
      processing: 'प्रक्रिया',
      transcribing: 'लिहित आहे',
      listen: 'ऐका',
      stop: 'थांबा',
      references: 'संदर्भ',
      onboarding: {
        talkToMe: 'माझ्याशी बोला',
        talkToMeDesc: 'फक्त माइक टॅप करा आणि तुमचा प्रश्न विचारा. मित्राशी बोलता तसे नैसर्गिकपणे बोला!',
        switchToText: 'टेक्स्टवर स्विच करा',
        switchToTextDesc: 'टाइप करणे आवडते? खालच्या बारमध्ये स्विच वापरून टेक्स्ट मोडवर जा.',
        uploadDocs: 'दस्तऐवज अपलोड करा',
        uploadDocsDesc: 'AI विश्लेषणासाठी कायदेशीर दस्तऐवज अपलोड करा. आम्ही PDF, DOCX, XLSX, CSV आणि प्रतिमांना सपोर्ट करतो.',
        listenResponses: 'उत्तरे ऐका',
        listenResponsesDesc: 'तुमच्या भाषेत ऐकण्यासाठी कोणत्याही उत्तरावर स्पीकर आयकॉनवर क्लिक करा.',
        skip: 'वगळा',
        next: 'पुढे',
        getStarted: 'सुरू करा',
        stepOf: 'पाऊल {current} चे {total}',
      },
    },
  },
  GU: {
    code: 'GU',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    fontClass: 'font-gujarati',
    direction: 'ltr',
    ttsVoice: 'gu-IN-Neural2-A',
    disclaimer: 'આ કાનૂની સલાહ નથી. ફક્ત સામાન્ય માહિતી.',
    ui: {
      startConsultation: 'કાનૂની સલાહ શરૂ કરો',
      tapToSpeak: 'બોલવા માટે ટૅપ કરો',
      listening: 'સાંભળી રહ્યો છું',
      analyzing: 'વિશ્લેષણ કરી રહ્યો છું',
      speaking: 'બોલી રહ્યો છું',
      uploadDocument: 'દસ્તાવેજ અપલોડ કરો',
      typeMessage: 'તમારો સંદેશ લખો...',
      send: 'મોકલો',
      emergency: 'કટોકટી',
      resources: 'સંસાધનો',
      info: 'માહિતી',
      admin: 'સંચાલક',
      startFresh: 'નવેસરથી શરૂ કરો',
      helpline: 'હેલ્પલાઇન',
      attach: 'જોડો',
      voice: 'અવાજ',
      text: 'ટેક્સ્ટ',
      connected: 'કનેક્ટેડ',
      offline: 'ઑફલાઇન',
      youSaid: 'તમે કહ્યું',
      welcomeMessage: 'નમસ્તે! હું ન્યાય સાથી, તમારો કાનૂની મિત્ર. આજે તમારા મનમાં શું છે? તમારા કાનૂની અધિકારો સમજવામાં મદદ કરવા હું અહીં છું.',
      thinking: 'વિચારી રહ્યો છું...',
      processing: 'પ્રોસેસિંગ',
      transcribing: 'લખી રહ્યો છું',
      listen: 'સાંભળો',
      stop: 'બંધ કરો',
      references: 'સંદર્ભો',
      onboarding: {
        talkToMe: 'મારી સાથે વાત કરો',
        talkToMeDesc: 'બસ માઇક ટેપ કરો અને તમારો પ્રશ્ન પૂછો. મિત્ર સાથે વાત કરો તેમ કુદરતી રીતે બોલો!',
        switchToText: 'ટેક્સ્ટ પર સ્વિચ કરો',
        switchToTextDesc: 'ટાઇપ કરવાનું પસંદ છે? નીચેની બારમાં સ્વિચ વાપરીને ટેક્સ્ટ મોડ પર જાઓ.',
        uploadDocs: 'દસ્તાવેજો અપલોડ કરો',
        uploadDocsDesc: 'AI વિશ્લેષણ માટે કાનૂની દસ્તાવેજો અપલોડ કરો. અમે PDF, DOCX, XLSX, CSV અને છબીઓને સપોર્ટ કરીએ છીએ.',
        listenResponses: 'જવાબો સાંભળો',
        listenResponsesDesc: 'તમારી ભાષામાં સાંભળવા માટે કોઈપણ જવાબ પર સ્પીકર આયકન ક્લિક કરો.',
        skip: 'છોડો',
        next: 'આગળ',
        getStarted: 'શરૂ કરો',
        stepOf: 'પગલું {current} માંથી {total}',
      },
    },
  },
  KN: {
    code: 'KN',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    fontClass: 'font-kannada',
    direction: 'ltr',
    ttsVoice: 'kn-IN-Neural2-A',
    disclaimer: 'ಇದು ಕಾನೂನು ಸಲಹೆ ಅಲ್ಲ. ಸಾಮಾನ್ಯ ಮಾಹಿತಿ ಮಾತ್ರ.',
    ui: {
      startConsultation: 'ಕಾನೂನು ಸಮಾಲೋಚನೆ ಪ್ರಾರಂಭಿಸಿ',
      tapToSpeak: 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
      listening: 'ಕೇಳುತ್ತಿದ್ದೇನೆ',
      analyzing: 'ವಿಶ್ಲೇಷಿಸುತ್ತಿದ್ದೇನೆ',
      speaking: 'ಮಾತನಾಡುತ್ತಿದ್ದೇನೆ',
      uploadDocument: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      typeMessage: 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
      send: 'ಕಳುಹಿಸಿ',
      emergency: 'ತುರ್ತು',
      resources: 'ಸಂಪನ್ಮೂಲಗಳು',
      info: 'ಮಾಹಿತಿ',
      admin: 'ನಿರ್ವಾಹಕ',
      startFresh: 'ಹೊಸದಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
      helpline: 'ಹೆಲ್ಪ್‌ಲೈನ್',
      attach: 'ಲಗತ್ತಿಸಿ',
      voice: 'ಧ್ವನಿ',
      text: 'ಪಠ್ಯ',
      connected: 'ಸಂಪರ್ಕಿತ',
      offline: 'ಆಫ್‌ಲೈನ್',
      youSaid: 'ನೀವು ಹೇಳಿದ್ದು',
      welcomeMessage: 'ನಮಸ್ಕಾರ! ನಾನು ನ್ಯಾಯ ಸಾಥಿ, ನಿಮ್ಮ ಕಾನೂನು ಸ್ನೇಹಿತ. ಇಂದು ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿ ಏನಿದೆ? ನಿಮ್ಮ ಕಾನೂನು ಹಕ್ಕುಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡಲು ನಾನು ಇಲ್ಲಿದ್ದೇನೆ.',
      thinking: 'ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ...',
      processing: 'ಪ್ರಕ್ರಿಯೆ',
      transcribing: 'ಬರೆಯುತ್ತಿದ್ದೇನೆ',
      listen: 'ಕೇಳಿ',
      stop: 'ನಿಲ್ಲಿಸಿ',
      references: 'ಉಲ್ಲೇಖಗಳು',
      onboarding: {
        talkToMe: 'ನನ್ನೊಂದಿಗೆ ಮಾತನಾಡಿ',
        talkToMeDesc: 'ಮೈಕ್ ಟ್ಯಾಪ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಪ್ರಶ್ನೆ ಕೇಳಿ. ಸ್ನೇಹಿತರೊಂದಿಗೆ ಮಾತನಾಡುವಂತೆ ಸಹಜವಾಗಿ ಮಾತನಾಡಿ!',
        switchToText: 'ಟೆಕ್ಸ್ಟ್ ಗೆ ಬದಲಿಸಿ',
        switchToTextDesc: 'ಟೈಪ್ ಮಾಡಲು ಇಷ್ಟಪಡುತ್ತೀರಾ? ಕೆಳಗಿನ ಬಾರ್‌ನಲ್ಲಿ ಸ್ವಿಚ್ ಬಳಸಿ ಟೆಕ್ಸ್ಟ್ ಮೋಡ್‌ಗೆ ಹೋಗಿ.',
        uploadDocs: 'ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
        uploadDocsDesc: 'AI ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ನಾವು PDF, DOCX, XLSX, CSV ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ಬೆಂಬಲಿಸುತ್ತೇವೆ.',
        listenResponses: 'ಉತ್ತರಗಳನ್ನು ಕೇಳಿ',
        listenResponsesDesc: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಕೇಳಲು ಯಾವುದೇ ಉತ್ತರದ ಮೇಲೆ ಸ್ಪೀಕರ್ ಐಕಾನ್ ಕ್ಲಿಕ್ ಮಾಡಿ.',
        skip: 'ಬಿಟ್ಟುಬಿಡಿ',
        next: 'ಮುಂದೆ',
        getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
        stepOf: 'ಹಂತ {current} ರಲ್ಲಿ {total}',
      },
    },
  },
  ML: {
    code: 'ML',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    fontClass: 'font-malayalam',
    direction: 'ltr',
    ttsVoice: 'ml-IN-Neural2-A',
    disclaimer: 'ഇത് നിയമ ഉപദേശമല്ല. പൊതു വിവരങ്ങൾ മാത്രം.',
    ui: {
      startConsultation: 'നിയമ കൺസൾട്ടേഷൻ ആരംഭിക്കുക',
      tapToSpeak: 'സംസാരിക്കാൻ ടാപ്പ് ചെയ്യുക',
      listening: 'കേൾക്കുന്നു',
      analyzing: 'വിശകലനം ചെയ്യുന്നു',
      speaking: 'സംസാരിക്കുന്നു',
      uploadDocument: 'രേഖ അപ്‌ലോഡ് ചെയ്യുക',
      typeMessage: 'നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
      send: 'അയയ്ക്കുക',
      emergency: 'അടിയന്തരം',
      resources: 'വിഭവങ്ങൾ',
      info: 'വിവരങ്ങൾ',
      admin: 'അഡ്മിൻ',
      startFresh: 'പുതുതായി തുടങ്ങുക',
      helpline: 'ഹെൽപ്പ്‌ലൈൻ',
      attach: 'അറ്റാച്ച് ചെയ്യുക',
      voice: 'ശബ്ദം',
      text: 'ടെക്സ്റ്റ്',
      connected: 'കണക്റ്റഡ്',
      offline: 'ഓഫ്‌ലൈൻ',
      youSaid: 'നിങ്ങൾ പറഞ്ഞത്',
      welcomeMessage: 'ഹലോ! ഞാൻ ന്യായ സാഥി, നിങ്ങളുടെ നിയമ സുഹൃത്ത്. ഇന്ന് നിങ്ങളുടെ മനസ്സിൽ എന്താണ്? നിങ്ങളുടെ നിയമ അവകാശങ്ങൾ മനസ്സിലാക്കാൻ സഹായിക്കാൻ ഞാൻ ഇവിടെയുണ്ട്.',
      thinking: 'ചിന്തിക്കുന്നു...',
      processing: 'പ്രോസസ്സിംഗ്',
      transcribing: 'എഴുതുന്നു',
      listen: 'കേൾക്കുക',
      stop: 'നിർത്തുക',
      references: 'റഫറൻസുകൾ',
      onboarding: {
        talkToMe: 'എന്നോട് സംസാരിക്കൂ',
        talkToMeDesc: 'മൈക്ക് ടാപ്പ് ചെയ്ത് നിങ്ങളുടെ ചോദ്യം ചോദിക്കൂ. ഒരു സുഹൃത്തിനോട് സംസാരിക്കുന്നത് പോലെ സ്വാഭാവികമായി സംസാരിക്കൂ!',
        switchToText: 'ടെക്സ്റ്റിലേക്ക് മാറുക',
        switchToTextDesc: 'ടൈപ്പ് ചെയ്യാൻ ഇഷ്ടപ്പെടുന്നോ? താഴെയുള്ള ബാറിലെ സ്വിച്ച് ഉപയോഗിച്ച് ടെക്സ്റ്റ് മോഡിലേക്ക് മാറുക.',
        uploadDocs: 'ഡോക്യുമെന്റുകൾ അപ്‌ലോഡ് ചെയ്യുക',
        uploadDocsDesc: 'AI വിശകലനത്തിനായി നിയമ ഡോക്യുമെന്റുകൾ അപ്‌ലോഡ് ചെയ്യുക. ഞങ്ങൾ PDF, DOCX, XLSX, CSV, ചിത്രങ്ങൾ എന്നിവ പിന്തുണയ്ക്കുന്നു.',
        listenResponses: 'മറുപടികൾ കേൾക്കുക',
        listenResponsesDesc: 'നിങ്ങളുടെ ഭാഷയിൽ കേൾക്കാൻ ഏതെങ്കിലും മറുപടിയിൽ സ്പീക്കർ ഐക്കണിൽ ക്ലിക്ക് ചെയ്യുക.',
        skip: 'ഒഴിവാക്കുക',
        next: 'അടുത്തത്',
        getStarted: 'ആരംഭിക്കുക',
        stepOf: 'ഘട്ടം {current} ൽ {total}',
      },
    },
  },
  PA: {
    code: 'PA',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    fontClass: 'font-punjabi',
    direction: 'ltr',
    ttsVoice: 'pa-IN-Neural2-A',
    disclaimer: 'ਇਹ ਕਾਨੂੰਨੀ ਸਲਾਹ ਨਹੀਂ ਹੈ। ਸਿਰਫ਼ ਆਮ ਜਾਣਕਾਰੀ।',
    ui: {
      startConsultation: 'ਕਾਨੂੰਨੀ ਸਲਾਹ ਸ਼ੁਰੂ ਕਰੋ',
      tapToSpeak: 'ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ',
      listening: 'ਸੁਣ ਰਿਹਾ ਹਾਂ',
      analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹਾਂ',
      speaking: 'ਬੋਲ ਰਿਹਾ ਹਾਂ',
      uploadDocument: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
      typeMessage: 'ਆਪਣਾ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...',
      send: 'ਭੇਜੋ',
      emergency: 'ਐਮਰਜੈਂਸੀ',
      resources: 'ਸਰੋਤ',
      info: 'ਜਾਣਕਾਰੀ',
      admin: 'ਪ੍ਰਬੰਧਕ',
      startFresh: 'ਨਵੇਂ ਸਿਰੇ ਤੋਂ ਸ਼ੁਰੂ ਕਰੋ',
      helpline: 'ਹੈਲਪਲਾਈਨ',
      attach: 'ਜੋੜੋ',
      voice: 'ਆਵਾਜ਼',
      text: 'ਟੈਕਸਟ',
      connected: 'ਕਨੈਕਟ',
      offline: 'ਆਫ਼ਲਾਈਨ',
      youSaid: 'ਤੁਸੀਂ ਕਿਹਾ',
      welcomeMessage: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਨਿਆਂ ਸਾਥੀ ਹਾਂ, ਤੁਹਾਡਾ ਕਾਨੂੰਨੀ ਦੋਸਤ। ਅੱਜ ਤੁਹਾਡੇ ਮਨ ਵਿੱਚ ਕੀ ਹੈ? ਮੈਂ ਤੁਹਾਡੇ ਕਾਨੂੰਨੀ ਹੱਕਾਂ ਨੂੰ ਸਮਝਣ ਵਿੱਚ ਮਦਦ ਕਰਨ ਲਈ ਇੱਥੇ ਹਾਂ।',
      thinking: 'ਸੋਚ ਰਿਹਾ ਹਾਂ...',
      processing: 'ਪ੍ਰੋਸੈਸਿੰਗ',
      transcribing: 'ਲਿਖ ਰਿਹਾ ਹਾਂ',
      listen: 'ਸੁਣੋ',
      stop: 'ਰੋਕੋ',
      references: 'ਹਵਾਲੇ',
      onboarding: {
        talkToMe: 'ਮੇਰੇ ਨਾਲ ਗੱਲ ਕਰੋ',
        talkToMeDesc: 'ਬੱਸ ਮਾਈਕ ਟੈਪ ਕਰੋ ਅਤੇ ਆਪਣਾ ਸਵਾਲ ਪੁੱਛੋ। ਦੋਸਤ ਨਾਲ ਗੱਲ ਕਰਦੇ ਹੋ ਜਿਵੇਂ ਕੁਦਰਤੀ ਤੌਰ ਤੇ ਬੋਲੋ!',
        switchToText: 'ਟੈਕਸਟ ਤੇ ਜਾਓ',
        switchToTextDesc: 'ਟਾਈਪ ਕਰਨਾ ਪਸੰਦ ਹੈ? ਹੇਠਲੀ ਬਾਰ ਵਿੱਚ ਸਵਿੱਚ ਵਰਤ ਕੇ ਟੈਕਸਟ ਮੋਡ ਤੇ ਜਾਓ।',
        uploadDocs: 'ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ',
        uploadDocsDesc: 'AI ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਕਾਨੂੰਨੀ ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰੋ। ਅਸੀਂ PDF, DOCX, XLSX, CSV ਅਤੇ ਤਸਵੀਰਾਂ ਦਾ ਸਮਰਥਨ ਕਰਦੇ ਹਾਂ।',
        listenResponses: 'ਜਵਾਬ ਸੁਣੋ',
        listenResponsesDesc: 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸੁਣਨ ਲਈ ਕਿਸੇ ਵੀ ਜਵਾਬ ਤੇ ਸਪੀਕਰ ਆਈਕਨ ਕਲਿੱਕ ਕਰੋ।',
        skip: 'ਛੱਡੋ',
        next: 'ਅਗਲਾ',
        getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
        stepOf: 'ਕਦਮ {current} ਵਿੱਚੋਂ {total}',
      },
    },
  },
  OR: {
    code: 'OR',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    fontClass: 'font-odia',
    direction: 'ltr',
    ttsVoice: 'or-IN-Standard-A',
    disclaimer: 'ଏହା ଆଇନଗତ ପରାମର୍ଶ ନୁହେଁ। କେବଳ ସାଧାରଣ ସୂଚନା।',
    ui: {
      startConsultation: 'ଆଇନଗତ ପରାମର୍ଶ ଆରମ୍ଭ କରନ୍ତୁ',
      tapToSpeak: 'କହିବାକୁ ଟ୍ୟାପ୍ କରନ୍ତୁ',
      listening: 'ଶୁଣୁଛି',
      analyzing: 'ବିଶ୍ଲେଷଣ କରୁଛି',
      speaking: 'କହୁଛି',
      uploadDocument: 'ଡକ୍ୟୁମେଣ୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
      typeMessage: 'ଆପଣଙ୍କ ସନ୍ଦେଶ ଟାଇପ୍ କରନ୍ତୁ...',
      send: 'ପଠାନ୍ତୁ',
      emergency: 'ଜରୁରୀ',
      resources: 'ସମ୍ବଳ',
      info: 'ସୂଚନା',
      admin: 'ପ୍ରଶାସକ',
      startFresh: 'ନୂଆରୁ ଆରମ୍ଭ କରନ୍ତୁ',
      helpline: 'ହେଲ୍ପଲାଇନ୍',
      attach: 'ସଂଲଗ୍ନ କରନ୍ତୁ',
      voice: 'ସ୍ୱର',
      text: 'ଟେକ୍ସଟ୍',
      connected: 'ସଂଯୁକ୍ତ',
      offline: 'ଅଫଲାଇନ୍',
      youSaid: 'ଆପଣ କହିଲେ',
      welcomeMessage: 'ନମସ୍କାର! ମୁଁ ନ୍ୟାୟ ସାଥୀ, ଆପଣଙ୍କ ଆଇନଗତ ସାଙ୍ଗ। ଆଜି ଆପଣଙ୍କ ମନରେ କଣ ଅଛି? ଆପଣଙ୍କ ଆଇନଗତ ଅଧିକାର ବୁଝିବାରେ ସାହାଯ୍ୟ କରିବାକୁ ମୁଁ ଏଠାରେ ଅଛି।',
      thinking: 'ଭାବୁଛି...',
      processing: 'ପ୍ରକ୍ରିୟାକରଣ',
      transcribing: 'ଲେଖୁଛି',
      listen: 'ଶୁଣନ୍ତୁ',
      stop: 'ବନ୍ଦ କରନ୍ତୁ',
      references: 'ସନ୍ଦର୍ଭ',
      onboarding: {
        talkToMe: 'ମୋ ସହ କଥା ହୁଅନ୍ତୁ',
        talkToMeDesc: 'ବସ୍ ମାଇକ୍ ଟ୍ୟାପ୍ କରନ୍ତୁ ଏବଂ ଆପଣଙ୍କ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ। ବନ୍ଧୁଙ୍କ ସହ କଥା ହେଉଥିବା ପରି ସ୍ୱାଭାବିକ ଭାବରେ କୁହନ୍ତୁ!',
        switchToText: 'ଟେକ୍ସଟ୍ କୁ ବଦଳାନ୍ତୁ',
        switchToTextDesc: 'ଟାଇପ୍ କରିବାକୁ ପସନ୍ଦ କରନ୍ତି? ତଳ ବାର୍‌ରେ ସ୍ୱିଚ୍ ବ୍ୟବହାର କରି ଟେକ୍ସଟ୍ ମୋଡ୍‌କୁ ଯାଆନ୍ତୁ।',
        uploadDocs: 'ଡକ୍ୟୁମେଣ୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ',
        uploadDocsDesc: 'AI ବିଶ୍ଲେଷଣ ପାଇଁ ଆଇନଗତ ଡକ୍ୟୁମେଣ୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ। ଆମେ PDF, DOCX, XLSX, CSV ଏବଂ ଚିତ୍ର ସମର୍ଥନ କରୁ।',
        listenResponses: 'ଉତ୍ତର ଶୁଣନ୍ତୁ',
        listenResponsesDesc: 'ଆପଣଙ୍କ ଭାଷାରେ ଶୁଣିବାକୁ ଯେକୌଣସି ଉତ୍ତରରେ ସ୍ପିକର୍ ଆଇକନ୍ କ୍ଲିକ୍ କରନ୍ତୁ।',
        skip: 'ଛାଡ଼ନ୍ତୁ',
        next: 'ପରବର୍ତ୍ତୀ',
        getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ',
        stepOf: 'ପାଦ {current} ର {total}',
      },
    },
  },
  UR: {
    code: 'UR',
    name: 'Urdu',
    nativeName: 'اردو',
    fontClass: 'font-urdu',
    direction: 'rtl',
    ttsVoice: 'ur-IN-Standard-A',
    disclaimer: 'یہ قانونی مشورہ نہیں ہے۔ صرف عام معلومات۔',
    ui: {
      startConsultation: 'قانونی مشاورت شروع کریں',
      tapToSpeak: 'بولنے کے لیے ٹیپ کریں',
      listening: 'سن رہا ہوں',
      analyzing: 'تجزیہ کر رہا ہوں',
      speaking: 'بول رہا ہوں',
      uploadDocument: 'دستاویز اپلوڈ کریں',
      typeMessage: 'اپنا پیغام ٹائپ کریں...',
      send: 'بھیجیں',
      emergency: 'ایمرجنسی',
      resources: 'وسائل',
      info: 'معلومات',
      admin: 'منتظم',
      startFresh: 'نئے سرے سے شروع کریں',
      helpline: 'ہیلپ لائن',
      attach: 'منسلک کریں',
      voice: 'آواز',
      text: 'ٹیکسٹ',
      connected: 'متصل',
      offline: 'آف لائن',
      youSaid: 'آپ نے کہا',
      welcomeMessage: 'السلام علیکم! میں نیائے ساتھی ہوں، آپ کا قانونی دوست۔ آج آپ کے ذہن میں کیا ہے؟ میں آپ کے قانونی حقوق سمجھنے میں مدد کرنے کے لیے یہاں ہوں۔',
      thinking: 'سوچ رہا ہوں...',
      processing: 'پروسیسنگ',
      transcribing: 'لکھ رہا ہوں',
      listen: 'سنیں',
      stop: 'روکیں',
      references: 'حوالہ جات',
      onboarding: {
        talkToMe: 'مجھ سے بات کریں',
        talkToMeDesc: 'بس مائیک ٹیپ کریں اور اپنا سوال پوچھیں۔ دوست سے بات کرتے ہیں جیسے قدرتی طور پر بولیں!',
        switchToText: 'ٹیکسٹ پر جائیں',
        switchToTextDesc: 'ٹائپ کرنا پسند ہے؟ نیچے کی بار میں سوئچ استعمال کرکے ٹیکسٹ موڈ پر جائیں۔',
        uploadDocs: 'دستاویزات اپلوڈ کریں',
        uploadDocsDesc: 'AI تجزیے کے لیے قانونی دستاویزات اپلوڈ کریں۔ ہم PDF، DOCX، XLSX، CSV اور تصاویر کی حمایت کرتے ہیں۔',
        listenResponses: 'جوابات سنیں',
        listenResponsesDesc: 'اپنی زبان میں سننے کے لیے کسی بھی جواب پر اسپیکر آئیکن پر کلک کریں۔',
        skip: 'چھوڑیں',
        next: 'اگلا',
        getStarted: 'شروع کریں',
        stepOf: 'قدم {current} میں سے {total}',
      },
    },
  },
};

export const DEFAULT_LANGUAGE: LanguageCode = 'EN';

export const getLanguageConfig = (code: LanguageCode): LanguageConfig => {
  return LANGUAGES[code] || LANGUAGES[DEFAULT_LANGUAGE];
};

export const getAllLanguages = (): LanguageConfig[] => {
  return Object.values(LANGUAGES);
};
